services:
  sandbox:
    build:
      context: ../..
      dockerfile: utils/oauth-mqtt/Dockerfile
    ports:
      - "8883:8883"
      - "8443:8443"
    environment:
      OAUTH_CONFIG_PATH: /app/sandbox.yaml
    volumes:
      - ./certs:/certs
      - ./sandbox.yaml:/app/sandbox.yaml
    restart: unless-stopped
