/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_CONNECT2_COMMAND_PB_H_INCLUDED
#define PB_CONNECT2_COMMAND_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Connect dialog button identifiers used both in old JSON and future protobuf.
 These string values historically appeared in the JSON buttons array and in
 kwargs.button when sending DIALOG_ACTION. */
typedef enum _connect2_DialogButton {
    connect2_DialogButton_DIALOG_BUTTON_UNSPECIFIED = 0,
    connect2_DialogButton_DIALOG_BUTTON_OK = 1,
    connect2_DialogButton_DIALOG_BUTTON_CANCEL = 2,
    connect2_DialogButton_DIALOG_BUTTON_YES = 3,
    connect2_DialogButton_DIALOG_BUTTON_NO = 4,
    connect2_DialogButton_DIALOG_BUTTON_RETRY = 5,
    connect2_DialogButton_DIALOG_BUTTON_ABORT = 6,
    connect2_DialogButton_DIALOG_BUTTON_IGNORE = 7,
    connect2_DialogButton_DIALOG_BUTTON_CONTINUE = 8,
    connect2_DialogButton_DIALOG_BUTTON_STOP = 9,
    connect2_DialogButton_DIALOG_BUTTON_PAUSE = 10,
    connect2_DialogButton_DIALOG_BUTTON_RESUME = 11,
    connect2_DialogButton_DIALOG_BUTTON_DONE = 12,
    connect2_DialogButton_DIALOG_BUTTON_COOLDOWN = 13,
    connect2_DialogButton_DIALOG_BUTTON_UNLOAD = 14,
    connect2_DialogButton_DIALOG_BUTTON_LOAD = 15
} connect2_DialogButton;

/* Property names accepted by old JSON SET_VALUE command.

 Many of these directly mirror old kwargs keys. The comments intentionally
 preserve the old JSON path spelling so that this enum becomes a migration
 index for future developers. */
typedef enum _connect2_SetValueProperty {
    connect2_SetValueProperty_SET_VALUE_PROPERTY_UNSPECIFIED = 0,
    /* Legacy JSON key: kwargs.hostname */
    connect2_SetValueProperty_SET_VALUE_PROPERTY_HOSTNAME = 1,
    /* Legacy JSON key: kwargs.enclosure_enabled */
    connect2_SetValueProperty_SET_VALUE_PROPERTY_ENCLOSURE_ENABLED = 2,
    /* Legacy JSON key: kwargs.enclosure_printing_filtration */
    connect2_SetValueProperty_SET_VALUE_PROPERTY_ENCLOSURE_PRINTING_FILTRATION = 3,
    /* Legacy JSON key: kwargs.enclosure_postprint */
    connect2_SetValueProperty_SET_VALUE_PROPERTY_ENCLOSURE_POSTPRINT = 4,
    /* Legacy JSON key: kwargs.enclosure_postprint_filtration_time */
    connect2_SetValueProperty_SET_VALUE_PROPERTY_ENCLOSURE_POSTPRINT_FILTRATION_TIME = 5,
    /* Legacy JSON keys:
 - kwargs.tools.<n>.nozzle_diameter */
    connect2_SetValueProperty_SET_VALUE_PROPERTY_NOZZLE_DIAMETER = 6,
    /* Legacy JSON keys:
 - kwargs.tools.<n>.high_flow */
    connect2_SetValueProperty_SET_VALUE_PROPERTY_NOZZLE_HIGH_FLOW = 7,
    /* Legacy JSON keys:
 - kwargs.tools.<n>.hardened */
    connect2_SetValueProperty_SET_VALUE_PROPERTY_NOZZLE_HARDENED = 8,
    /* Legacy JSON key: kwargs.chamber.target_temp */
    connect2_SetValueProperty_SET_VALUE_PROPERTY_CHAMBER_TARGET_TEMP = 9,
    /* Legacy JSON key: kwargs.chamber.fan_pwm_target */
    connect2_SetValueProperty_SET_VALUE_PROPERTY_CHAMBER_FAN_PWM_TARGET = 10,
    /* Legacy JSON key: kwargs.addon_power */
    connect2_SetValueProperty_SET_VALUE_PROPERTY_ADDON_POWER = 11,
    /* Legacy JSON key: kwargs.chamber.led_intensity */
    connect2_SetValueProperty_SET_VALUE_PROPERTY_CHAMBER_LED_INTENSITY = 12
} connect2_SetValueProperty;

/* Struct definitions */
/* Replaces legacy JSON command:
 {
   "command": "SEND_INFO",
   "kwargs": {}
 }

 Purpose:
 Ask the printer to emit an INFO event immediately. */
typedef struct _connect2_SendInfoCommand {
    char dummy_field;
} connect2_SendInfoCommand;

/* Replaces legacy JSON command:
 {
   "command": "SEND_JOB_INFO",
   "kwargs": {
     "job_id": 123
   }
 }

 Legacy behavior:
 - job_id was optional
 - if job_id was present, firmware rejected mismatched active job id
 - if no job was active, firmware rejected the request */
typedef struct _connect2_SendJobInfoCommand {
    /* True when the request carries the legacy kwargs.job_id filter. */
    bool has_job_id;
    /* Legacy JSON key: kwargs.job_id */
    uint32_t job_id;
} connect2_SendJobInfoCommand;

/* Replaces legacy JSON command:
 {
   "command": "SEND_FILE_INFO",
   "kwargs": {
     "path": "/usb"
   }
 }

 Legacy aliases:
 - path
 - path_sfn

 Purpose:
 Ask the printer to emit FILE_INFO for a file or directory on USB. */
typedef struct _connect2_SendFileInfoCommand {
    /* Legacy JSON key: kwargs.path or kwargs.path_sfn */
    pb_callback_t path;
} connect2_SendFileInfoCommand;

/* Replaces legacy JSON command:
 {
   "command": "SEND_TRANSFER_INFO",
   "kwargs": {}
 }

 Purpose:
 Ask the printer to emit current transfer progress/state. */
typedef struct _connect2_SendTransferInfoCommand {
    char dummy_field;
} connect2_SendTransferInfoCommand;

/* Replaces legacy JSON command:
 {
   "command": "PAUSE_PRINT",
   "kwargs": {}
 } */
typedef struct _connect2_PausePrintCommand {
    char dummy_field;
} connect2_PausePrintCommand;

/* Replaces legacy JSON command:
 {
   "command": "RESUME_PRINT",
   "kwargs": {}
 } */
typedef struct _connect2_ResumePrintCommand {
    char dummy_field;
} connect2_ResumePrintCommand;

/* Replaces legacy JSON command:
 {
   "command": "STOP_PRINT",
   "kwargs": {}
 } */
typedef struct _connect2_StopPrintCommand {
    char dummy_field;
} connect2_StopPrintCommand;

/* Old Connect supported optional tool mapping in START_PRINT.
 The JSON parser accepted a nested kwargs.tool_mapping object.

 External tool numbering in JSON was 1-based.
 Firmware-side internal mapping historically used 0-based indices. */
typedef struct _connect2_ToolMappingPair {
    /* External tool slot number as seen by Connect JSON. */
    uint32_t source_tool;
    /* External target tool number as seen by Connect JSON. */
    uint32_t target_tool;
} connect2_ToolMappingPair;

/* Replaces legacy JSON command:
 {
   "command": "START_PRINT",
   "kwargs": {
     "path": "/usb/file.bgcode",
     "tool_mapping": {
       "1": [1, 2, ...]
     }
   }
 }

 In practice the first firmware milestone may only use path and ignore
 tool_mapping, but the schema documents the full intended legacy replacement. */
typedef struct _connect2_StartPrintCommand {
    /* Legacy JSON key: kwargs.path or kwargs.path_sfn */
    pb_callback_t path;
    /* Optional flattened representation of legacy kwargs.tool_mapping.
 We intentionally flatten it instead of encoding a sparse nested map so the
 schema remains easier to use from constrained code generators. */
    pb_callback_t tool_mapping;
} connect2_StartPrintCommand;

/* Replaces legacy JSON command:
 {
   "command": "SET_PRINTER_READY",
   "kwargs": {}
 } */
typedef struct _connect2_SetPrinterReadyCommand {
    char dummy_field;
} connect2_SetPrinterReadyCommand;

/* Replaces legacy JSON command:
 {
   "command": "CANCEL_PRINTER_READY",
   "kwargs": {}
 } */
typedef struct _connect2_CancelPrinterReadyCommand {
    char dummy_field;
} connect2_CancelPrinterReadyCommand;

/* Replaces legacy JSON command:
 {
   "command": "SET_IDLE",
   "kwargs": {}
 } */
typedef struct _connect2_SetIdleCommand {
    char dummy_field;
} connect2_SetIdleCommand;

/* Replaces legacy JSON command:
 {
   "command": "DELETE_FILE",
   "kwargs": {
     "path": "/usb/file.gcode"
   }
 } */
typedef struct _connect2_DeleteFileCommand {
    pb_callback_t path;
} connect2_DeleteFileCommand;

/* Replaces legacy JSON command:
 {
   "command": "DELETE_FOLDER",
   "kwargs": {
     "path": "/usb/folder"
   }
 } */
typedef struct _connect2_DeleteFolderCommand {
    pb_callback_t path;
} connect2_DeleteFolderCommand;

/* Replaces legacy JSON command:
 {
   "command": "CREATE_FOLDER",
   "kwargs": {
     "path": "/usb/new-folder"
   }
 } */
typedef struct _connect2_CreateFolderCommand {
    pb_callback_t path;
} connect2_CreateFolderCommand;

/* Replaces legacy JSON command:
 {
   "command": "STOP_TRANSFER",
   "kwargs": {}
 } */
typedef struct _connect2_StopTransferCommand {
    char dummy_field;
} connect2_StopTransferCommand;

/* Replaces legacy JSON command:
 {
   "command": "SET_TOKEN",
   "kwargs": {
     "token": "..."
   }
 }

 This was part of older Connect registration/token flows. Our current
 CONNECT2 OAuth/JWT path may never need it operationally, but we keep it in
 the schema because it is part of the legacy JSON protocol surface. */
typedef struct _connect2_SetTokenCommand {
    /* Legacy JSON key: kwargs.token */
    pb_callback_t token;
} connect2_SetTokenCommand;

/* Replaces either of the legacy JSON commands:
 {
   "command": "RESET_PRINTER",
   "kwargs": {}
 }
 or
 {
   "command": "RESET",
   "kwargs": {}
 }

 Legacy behavior treated both spellings the same on Buddy. */
typedef struct _connect2_ResetPrinterCommand {
    /* True if the original upstream JSON command string was exactly "RESET".
 This is not required for printer behavior, but it is useful if the proxy
 ever wants to preserve exact legacy spelling for debugging. */
    bool legacy_reset_alias;
} connect2_ResetPrinterCommand;

/* Replaces legacy JSON command:
 {
   "command": "SEND_STATE_INFO",
   "kwargs": {}
 } */
typedef struct _connect2_SendStateInfoCommand {
    char dummy_field;
} connect2_SendStateInfoCommand;

/* Replaces legacy JSON command:
 {
   "command": "DIALOG_ACTION",
   "kwargs": {
     "dialog_id": 123,
     "button": "YES"
   }
 } */
typedef struct _connect2_DialogActionCommand {
    /* Legacy JSON key: kwargs.dialog_id */
    uint32_t dialog_id;
    /* Legacy JSON key: kwargs.button */
    connect2_DialogButton button;
} connect2_DialogActionCommand;

/* Replaces legacy JSON command:
 {
   "command": "SET_VALUE",
   "kwargs": {
     ... one supported property encoded as a key-value pair ...
   }
 }

 Legacy SET_VALUE was unusual: the property name was encoded as the key name
 in kwargs rather than as a value of a field named "property".

 This protobuf form normalizes the legacy shape into:
 - a typed property enum
 - an optional tool index for per-tool values
 - one strongly typed value payload */
typedef struct _connect2_SetValueCommand {
    connect2_SetValueProperty property;
    /* Used for per-tool properties such as nozzle diameter/high_flow/hardened.
 Keep 1-based external numbering to match Connect-facing semantics. */
    uint32_t tool_index;
    pb_size_t which_value;
    union {
        bool bool_value;
        uint32_t uint32_value;
        int32_t int32_value;
        float float_value;
        pb_callback_t string_value;
    } value;
} connect2_SetValueCommand;

/* Replaces legacy JSON command:
 {
   "command": "CANCEL_OBJECT",
   "kwargs": {
     "id": 3
   }
 } */
typedef struct _connect2_CancelObjectCommand {
    /* Legacy JSON key: kwargs.id */
    uint32_t object_id;
} connect2_CancelObjectCommand;

/* Replaces legacy JSON command:
 {
   "command": "UNCANCEL_OBJECT",
   "kwargs": {
     "id": 3
   }
 } */
typedef struct _connect2_UncancelObjectCommand {
    /* Legacy JSON key: kwargs.id */
    uint32_t object_id;
} connect2_UncancelObjectCommand;

/* Replaces legacy JSON command:
 {
   "command": "START_INLINE_DOWNLOAD",
   "kwargs": {
     "path": "/usb/file.gcode",
     "orig_size": 123456,
     "team_id": 42,
     "hash": "base64-or-fingerprint"
   }
 }

 Legacy note:
 START_CONNECT_DOWNLOAD was parsed exactly like START_INLINE_DOWNLOAD in
 Buddy firmware. The naming difference came from server-side routing choices. */
typedef struct _connect2_StartInlineDownloadCommand {
    pb_callback_t path;
    uint32_t orig_size;
    uint64_t team_id;
    pb_callback_t hash;
} connect2_StartInlineDownloadCommand;

/* Replaces legacy JSON command:
 {
   "command": "START_CONNECT_DOWNLOAD",
   "kwargs": {
     "path": "/usb/file.gcode",
     "orig_size": 123456,
     "team_id": 42,
     "hash": "base64-or-fingerprint"
   }
 }

 We keep this as a distinct protobuf message so the proxy can preserve exact
 legacy intent if needed, even though old Buddy firmware handled it the same
 way as START_INLINE_DOWNLOAD. */
typedef struct _connect2_StartConnectDownloadCommand {
    pb_callback_t path;
    uint32_t orig_size;
    uint64_t team_id;
    pb_callback_t hash;
} connect2_StartConnectDownloadCommand;

/* Replaces legacy JSON command:
 {
   "command": "START_ENCRYPTED_DOWNLOAD",
   "kwargs": {
     "path": "/usb/file.gcode",
     "orig_size": 123456,
     "key": "hex-encoded 16-byte key",
     "iv": "hex-encoded 16-byte iv-or-nonce",
     "port": 1234
   }
 }

 Historical note:
 Legacy code comments mention that iv kept its old AES-CBC name even after the
 implementation moved to AES-CTR semantics, where it behaves as a nonce. */
typedef struct _connect2_StartEncryptedDownloadCommand {
    pb_callback_t path;
    uint32_t orig_size;
    /* Raw binary 16-byte key. Legacy JSON used a hex string in kwargs.key. */
    pb_callback_t key;
    /* Raw binary 16-byte iv/nonce. Legacy JSON used a hex string in kwargs.iv. */
    pb_callback_t iv;
    /* Legacy JSON key: kwargs.port. Optional override in old JSON parser. */
    bool has_port;
    uint32_t port;
} connect2_StartEncryptedDownloadCommand;

/* Top-level command envelope sent from proxy/server to printer over MQTT.

 Replaces many legacy JSON commands that were previously delivered over the
 WebSocket path and parsed in src/connect/command.cpp. */
typedef struct _connect2_CommandEnvelope {
    /* Legacy meaning: command identifier associated with the incoming command.
 In old Connect code this was not encoded as a JSON field in the inner
 command payload, but it existed as command metadata throughout the planner. */
    uint32_t command_id;
    pb_size_t which_payload;
    union {
        connect2_SendInfoCommand send_info;
        connect2_SendJobInfoCommand send_job_info;
        connect2_SendFileInfoCommand send_file_info;
        connect2_SendTransferInfoCommand send_transfer_info;
        connect2_PausePrintCommand pause_print;
        connect2_ResumePrintCommand resume_print;
        connect2_StopPrintCommand stop_print;
        connect2_StartPrintCommand start_print;
        connect2_SetPrinterReadyCommand set_printer_ready;
        connect2_CancelPrinterReadyCommand cancel_printer_ready;
        connect2_SetIdleCommand set_idle;
        connect2_DeleteFileCommand delete_file;
        connect2_DeleteFolderCommand delete_folder;
        connect2_CreateFolderCommand create_folder;
        connect2_StopTransferCommand stop_transfer;
        connect2_SetTokenCommand set_token;
        connect2_ResetPrinterCommand reset_printer;
        connect2_SendStateInfoCommand send_state_info;
        connect2_DialogActionCommand dialog_action;
        connect2_SetValueCommand set_value;
        connect2_CancelObjectCommand cancel_object;
        connect2_UncancelObjectCommand uncancel_object;
        connect2_StartInlineDownloadCommand start_inline_download;
        connect2_StartConnectDownloadCommand start_connect_download;
        connect2_StartEncryptedDownloadCommand start_encrypted_download;
    } payload;
} connect2_CommandEnvelope;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _connect2_DialogButton_MIN connect2_DialogButton_DIALOG_BUTTON_UNSPECIFIED
#define _connect2_DialogButton_MAX connect2_DialogButton_DIALOG_BUTTON_LOAD
#define _connect2_DialogButton_ARRAYSIZE ((connect2_DialogButton)(connect2_DialogButton_DIALOG_BUTTON_LOAD+1))

#define _connect2_SetValueProperty_MIN connect2_SetValueProperty_SET_VALUE_PROPERTY_UNSPECIFIED
#define _connect2_SetValueProperty_MAX connect2_SetValueProperty_SET_VALUE_PROPERTY_CHAMBER_LED_INTENSITY
#define _connect2_SetValueProperty_ARRAYSIZE ((connect2_SetValueProperty)(connect2_SetValueProperty_SET_VALUE_PROPERTY_CHAMBER_LED_INTENSITY+1))





















#define connect2_DialogActionCommand_button_ENUMTYPE connect2_DialogButton

#define connect2_SetValueCommand_property_ENUMTYPE connect2_SetValueProperty







/* Initializer values for message structs */
#define connect2_CommandEnvelope_init_default    {0, 0, {connect2_SendInfoCommand_init_default}}
#define connect2_SendInfoCommand_init_default    {0}
#define connect2_SendJobInfoCommand_init_default {0, 0}
#define connect2_SendFileInfoCommand_init_default {{{NULL}, NULL}}
#define connect2_SendTransferInfoCommand_init_default {0}
#define connect2_PausePrintCommand_init_default  {0}
#define connect2_ResumePrintCommand_init_default {0}
#define connect2_StopPrintCommand_init_default   {0}
#define connect2_ToolMappingPair_init_default    {0, 0}
#define connect2_StartPrintCommand_init_default  {{{NULL}, NULL}, {{NULL}, NULL}}
#define connect2_SetPrinterReadyCommand_init_default {0}
#define connect2_CancelPrinterReadyCommand_init_default {0}
#define connect2_SetIdleCommand_init_default     {0}
#define connect2_DeleteFileCommand_init_default  {{{NULL}, NULL}}
#define connect2_DeleteFolderCommand_init_default {{{NULL}, NULL}}
#define connect2_CreateFolderCommand_init_default {{{NULL}, NULL}}
#define connect2_StopTransferCommand_init_default {0}
#define connect2_SetTokenCommand_init_default    {{{NULL}, NULL}}
#define connect2_ResetPrinterCommand_init_default {0}
#define connect2_SendStateInfoCommand_init_default {0}
#define connect2_DialogActionCommand_init_default {0, _connect2_DialogButton_MIN}
#define connect2_SetValueCommand_init_default    {_connect2_SetValueProperty_MIN, 0, 0, {0}}
#define connect2_CancelObjectCommand_init_default {0}
#define connect2_UncancelObjectCommand_init_default {0}
#define connect2_StartInlineDownloadCommand_init_default {{{NULL}, NULL}, 0, 0, {{NULL}, NULL}}
#define connect2_StartConnectDownloadCommand_init_default {{{NULL}, NULL}, 0, 0, {{NULL}, NULL}}
#define connect2_StartEncryptedDownloadCommand_init_default {{{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0}
#define connect2_CommandEnvelope_init_zero       {0, 0, {connect2_SendInfoCommand_init_zero}}
#define connect2_SendInfoCommand_init_zero       {0}
#define connect2_SendJobInfoCommand_init_zero    {0, 0}
#define connect2_SendFileInfoCommand_init_zero   {{{NULL}, NULL}}
#define connect2_SendTransferInfoCommand_init_zero {0}
#define connect2_PausePrintCommand_init_zero     {0}
#define connect2_ResumePrintCommand_init_zero    {0}
#define connect2_StopPrintCommand_init_zero      {0}
#define connect2_ToolMappingPair_init_zero       {0, 0}
#define connect2_StartPrintCommand_init_zero     {{{NULL}, NULL}, {{NULL}, NULL}}
#define connect2_SetPrinterReadyCommand_init_zero {0}
#define connect2_CancelPrinterReadyCommand_init_zero {0}
#define connect2_SetIdleCommand_init_zero        {0}
#define connect2_DeleteFileCommand_init_zero     {{{NULL}, NULL}}
#define connect2_DeleteFolderCommand_init_zero   {{{NULL}, NULL}}
#define connect2_CreateFolderCommand_init_zero   {{{NULL}, NULL}}
#define connect2_StopTransferCommand_init_zero   {0}
#define connect2_SetTokenCommand_init_zero       {{{NULL}, NULL}}
#define connect2_ResetPrinterCommand_init_zero   {0}
#define connect2_SendStateInfoCommand_init_zero  {0}
#define connect2_DialogActionCommand_init_zero   {0, _connect2_DialogButton_MIN}
#define connect2_SetValueCommand_init_zero       {_connect2_SetValueProperty_MIN, 0, 0, {0}}
#define connect2_CancelObjectCommand_init_zero   {0}
#define connect2_UncancelObjectCommand_init_zero {0}
#define connect2_StartInlineDownloadCommand_init_zero {{{NULL}, NULL}, 0, 0, {{NULL}, NULL}}
#define connect2_StartConnectDownloadCommand_init_zero {{{NULL}, NULL}, 0, 0, {{NULL}, NULL}}
#define connect2_StartEncryptedDownloadCommand_init_zero {{{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define connect2_SendJobInfoCommand_has_job_id_tag 1
#define connect2_SendJobInfoCommand_job_id_tag   2
#define connect2_SendFileInfoCommand_path_tag    1
#define connect2_ToolMappingPair_source_tool_tag 1
#define connect2_ToolMappingPair_target_tool_tag 2
#define connect2_StartPrintCommand_path_tag      1
#define connect2_StartPrintCommand_tool_mapping_tag 2
#define connect2_DeleteFileCommand_path_tag      1
#define connect2_DeleteFolderCommand_path_tag    1
#define connect2_CreateFolderCommand_path_tag    1
#define connect2_SetTokenCommand_token_tag       1
#define connect2_ResetPrinterCommand_legacy_reset_alias_tag 1
#define connect2_DialogActionCommand_dialog_id_tag 1
#define connect2_DialogActionCommand_button_tag  2
#define connect2_SetValueCommand_property_tag    1
#define connect2_SetValueCommand_tool_index_tag  2
#define connect2_SetValueCommand_bool_value_tag  10
#define connect2_SetValueCommand_uint32_value_tag 11
#define connect2_SetValueCommand_int32_value_tag 12
#define connect2_SetValueCommand_float_value_tag 13
#define connect2_SetValueCommand_string_value_tag 14
#define connect2_CancelObjectCommand_object_id_tag 1
#define connect2_UncancelObjectCommand_object_id_tag 1
#define connect2_StartInlineDownloadCommand_path_tag 1
#define connect2_StartInlineDownloadCommand_orig_size_tag 2
#define connect2_StartInlineDownloadCommand_team_id_tag 3
#define connect2_StartInlineDownloadCommand_hash_tag 4
#define connect2_StartConnectDownloadCommand_path_tag 1
#define connect2_StartConnectDownloadCommand_orig_size_tag 2
#define connect2_StartConnectDownloadCommand_team_id_tag 3
#define connect2_StartConnectDownloadCommand_hash_tag 4
#define connect2_StartEncryptedDownloadCommand_path_tag 1
#define connect2_StartEncryptedDownloadCommand_orig_size_tag 2
#define connect2_StartEncryptedDownloadCommand_key_tag 3
#define connect2_StartEncryptedDownloadCommand_iv_tag 4
#define connect2_StartEncryptedDownloadCommand_has_port_tag 5
#define connect2_StartEncryptedDownloadCommand_port_tag 6
#define connect2_CommandEnvelope_command_id_tag  1
#define connect2_CommandEnvelope_send_info_tag   10
#define connect2_CommandEnvelope_send_job_info_tag 11
#define connect2_CommandEnvelope_send_file_info_tag 12
#define connect2_CommandEnvelope_send_transfer_info_tag 13
#define connect2_CommandEnvelope_pause_print_tag 14
#define connect2_CommandEnvelope_resume_print_tag 15
#define connect2_CommandEnvelope_stop_print_tag  16
#define connect2_CommandEnvelope_start_print_tag 17
#define connect2_CommandEnvelope_set_printer_ready_tag 18
#define connect2_CommandEnvelope_cancel_printer_ready_tag 19
#define connect2_CommandEnvelope_set_idle_tag    20
#define connect2_CommandEnvelope_delete_file_tag 21
#define connect2_CommandEnvelope_delete_folder_tag 22
#define connect2_CommandEnvelope_create_folder_tag 23
#define connect2_CommandEnvelope_stop_transfer_tag 24
#define connect2_CommandEnvelope_set_token_tag   25
#define connect2_CommandEnvelope_reset_printer_tag 26
#define connect2_CommandEnvelope_send_state_info_tag 27
#define connect2_CommandEnvelope_dialog_action_tag 28
#define connect2_CommandEnvelope_set_value_tag   29
#define connect2_CommandEnvelope_cancel_object_tag 30
#define connect2_CommandEnvelope_uncancel_object_tag 31
#define connect2_CommandEnvelope_start_inline_download_tag 32
#define connect2_CommandEnvelope_start_connect_download_tag 33
#define connect2_CommandEnvelope_start_encrypted_download_tag 34

/* Struct field encoding specification for nanopb */
#define connect2_CommandEnvelope_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   command_id,        1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,send_info,payload.send_info),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,send_job_info,payload.send_job_info),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,send_file_info,payload.send_file_info),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,send_transfer_info,payload.send_transfer_info),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,pause_print,payload.pause_print),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,resume_print,payload.resume_print),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,stop_print,payload.stop_print),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,start_print,payload.start_print),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_printer_ready,payload.set_printer_ready),  18) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,cancel_printer_ready,payload.cancel_printer_ready),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_idle,payload.set_idle),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,delete_file,payload.delete_file),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,delete_folder,payload.delete_folder),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,create_folder,payload.create_folder),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,stop_transfer,payload.stop_transfer),  24) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_token,payload.set_token),  25) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,reset_printer,payload.reset_printer),  26) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,send_state_info,payload.send_state_info),  27) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,dialog_action,payload.dialog_action),  28) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_value,payload.set_value),  29) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,cancel_object,payload.cancel_object),  30) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,uncancel_object,payload.uncancel_object),  31) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,start_inline_download,payload.start_inline_download),  32) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,start_connect_download,payload.start_connect_download),  33) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,start_encrypted_download,payload.start_encrypted_download),  34)
#define connect2_CommandEnvelope_CALLBACK NULL
#define connect2_CommandEnvelope_DEFAULT NULL
#define connect2_CommandEnvelope_payload_send_info_MSGTYPE connect2_SendInfoCommand
#define connect2_CommandEnvelope_payload_send_job_info_MSGTYPE connect2_SendJobInfoCommand
#define connect2_CommandEnvelope_payload_send_file_info_MSGTYPE connect2_SendFileInfoCommand
#define connect2_CommandEnvelope_payload_send_transfer_info_MSGTYPE connect2_SendTransferInfoCommand
#define connect2_CommandEnvelope_payload_pause_print_MSGTYPE connect2_PausePrintCommand
#define connect2_CommandEnvelope_payload_resume_print_MSGTYPE connect2_ResumePrintCommand
#define connect2_CommandEnvelope_payload_stop_print_MSGTYPE connect2_StopPrintCommand
#define connect2_CommandEnvelope_payload_start_print_MSGTYPE connect2_StartPrintCommand
#define connect2_CommandEnvelope_payload_set_printer_ready_MSGTYPE connect2_SetPrinterReadyCommand
#define connect2_CommandEnvelope_payload_cancel_printer_ready_MSGTYPE connect2_CancelPrinterReadyCommand
#define connect2_CommandEnvelope_payload_set_idle_MSGTYPE connect2_SetIdleCommand
#define connect2_CommandEnvelope_payload_delete_file_MSGTYPE connect2_DeleteFileCommand
#define connect2_CommandEnvelope_payload_delete_folder_MSGTYPE connect2_DeleteFolderCommand
#define connect2_CommandEnvelope_payload_create_folder_MSGTYPE connect2_CreateFolderCommand
#define connect2_CommandEnvelope_payload_stop_transfer_MSGTYPE connect2_StopTransferCommand
#define connect2_CommandEnvelope_payload_set_token_MSGTYPE connect2_SetTokenCommand
#define connect2_CommandEnvelope_payload_reset_printer_MSGTYPE connect2_ResetPrinterCommand
#define connect2_CommandEnvelope_payload_send_state_info_MSGTYPE connect2_SendStateInfoCommand
#define connect2_CommandEnvelope_payload_dialog_action_MSGTYPE connect2_DialogActionCommand
#define connect2_CommandEnvelope_payload_set_value_MSGTYPE connect2_SetValueCommand
#define connect2_CommandEnvelope_payload_cancel_object_MSGTYPE connect2_CancelObjectCommand
#define connect2_CommandEnvelope_payload_uncancel_object_MSGTYPE connect2_UncancelObjectCommand
#define connect2_CommandEnvelope_payload_start_inline_download_MSGTYPE connect2_StartInlineDownloadCommand
#define connect2_CommandEnvelope_payload_start_connect_download_MSGTYPE connect2_StartConnectDownloadCommand
#define connect2_CommandEnvelope_payload_start_encrypted_download_MSGTYPE connect2_StartEncryptedDownloadCommand

#define connect2_SendInfoCommand_FIELDLIST(X, a) \

#define connect2_SendInfoCommand_CALLBACK NULL
#define connect2_SendInfoCommand_DEFAULT NULL

#define connect2_SendJobInfoCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     has_job_id,        1) \
X(a, STATIC,   SINGULAR, UINT32,   job_id,            2)
#define connect2_SendJobInfoCommand_CALLBACK NULL
#define connect2_SendJobInfoCommand_DEFAULT NULL

#define connect2_SendFileInfoCommand_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   path,              1)
#define connect2_SendFileInfoCommand_CALLBACK pb_default_field_callback
#define connect2_SendFileInfoCommand_DEFAULT NULL

#define connect2_SendTransferInfoCommand_FIELDLIST(X, a) \

#define connect2_SendTransferInfoCommand_CALLBACK NULL
#define connect2_SendTransferInfoCommand_DEFAULT NULL

#define connect2_PausePrintCommand_FIELDLIST(X, a) \

#define connect2_PausePrintCommand_CALLBACK NULL
#define connect2_PausePrintCommand_DEFAULT NULL

#define connect2_ResumePrintCommand_FIELDLIST(X, a) \

#define connect2_ResumePrintCommand_CALLBACK NULL
#define connect2_ResumePrintCommand_DEFAULT NULL

#define connect2_StopPrintCommand_FIELDLIST(X, a) \

#define connect2_StopPrintCommand_CALLBACK NULL
#define connect2_StopPrintCommand_DEFAULT NULL

#define connect2_ToolMappingPair_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   source_tool,       1) \
X(a, STATIC,   SINGULAR, UINT32,   target_tool,       2)
#define connect2_ToolMappingPair_CALLBACK NULL
#define connect2_ToolMappingPair_DEFAULT NULL

#define connect2_StartPrintCommand_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   path,              1) \
X(a, CALLBACK, REPEATED, MESSAGE,  tool_mapping,      2)
#define connect2_StartPrintCommand_CALLBACK pb_default_field_callback
#define connect2_StartPrintCommand_DEFAULT NULL
#define connect2_StartPrintCommand_tool_mapping_MSGTYPE connect2_ToolMappingPair

#define connect2_SetPrinterReadyCommand_FIELDLIST(X, a) \

#define connect2_SetPrinterReadyCommand_CALLBACK NULL
#define connect2_SetPrinterReadyCommand_DEFAULT NULL

#define connect2_CancelPrinterReadyCommand_FIELDLIST(X, a) \

#define connect2_CancelPrinterReadyCommand_CALLBACK NULL
#define connect2_CancelPrinterReadyCommand_DEFAULT NULL

#define connect2_SetIdleCommand_FIELDLIST(X, a) \

#define connect2_SetIdleCommand_CALLBACK NULL
#define connect2_SetIdleCommand_DEFAULT NULL

#define connect2_DeleteFileCommand_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   path,              1)
#define connect2_DeleteFileCommand_CALLBACK pb_default_field_callback
#define connect2_DeleteFileCommand_DEFAULT NULL

#define connect2_DeleteFolderCommand_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   path,              1)
#define connect2_DeleteFolderCommand_CALLBACK pb_default_field_callback
#define connect2_DeleteFolderCommand_DEFAULT NULL

#define connect2_CreateFolderCommand_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   path,              1)
#define connect2_CreateFolderCommand_CALLBACK pb_default_field_callback
#define connect2_CreateFolderCommand_DEFAULT NULL

#define connect2_StopTransferCommand_FIELDLIST(X, a) \

#define connect2_StopTransferCommand_CALLBACK NULL
#define connect2_StopTransferCommand_DEFAULT NULL

#define connect2_SetTokenCommand_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   token,             1)
#define connect2_SetTokenCommand_CALLBACK pb_default_field_callback
#define connect2_SetTokenCommand_DEFAULT NULL

#define connect2_ResetPrinterCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     legacy_reset_alias,   1)
#define connect2_ResetPrinterCommand_CALLBACK NULL
#define connect2_ResetPrinterCommand_DEFAULT NULL

#define connect2_SendStateInfoCommand_FIELDLIST(X, a) \

#define connect2_SendStateInfoCommand_CALLBACK NULL
#define connect2_SendStateInfoCommand_DEFAULT NULL

#define connect2_DialogActionCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dialog_id,         1) \
X(a, STATIC,   SINGULAR, UENUM,    button,            2)
#define connect2_DialogActionCommand_CALLBACK NULL
#define connect2_DialogActionCommand_DEFAULT NULL

#define connect2_SetValueCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    property,          1) \
X(a, STATIC,   SINGULAR, UINT32,   tool_index,        2) \
X(a, STATIC,   ONEOF,    BOOL,     (value,bool_value,value.bool_value),  10) \
X(a, STATIC,   ONEOF,    UINT32,   (value,uint32_value,value.uint32_value),  11) \
X(a, STATIC,   ONEOF,    SINT32,   (value,int32_value,value.int32_value),  12) \
X(a, STATIC,   ONEOF,    FLOAT,    (value,float_value,value.float_value),  13) \
X(a, CALLBACK, ONEOF,    STRING,   (value,string_value,value.string_value),  14)
#define connect2_SetValueCommand_CALLBACK pb_default_field_callback
#define connect2_SetValueCommand_DEFAULT NULL

#define connect2_CancelObjectCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   object_id,         1)
#define connect2_CancelObjectCommand_CALLBACK NULL
#define connect2_CancelObjectCommand_DEFAULT NULL

#define connect2_UncancelObjectCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   object_id,         1)
#define connect2_UncancelObjectCommand_CALLBACK NULL
#define connect2_UncancelObjectCommand_DEFAULT NULL

#define connect2_StartInlineDownloadCommand_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   path,              1) \
X(a, STATIC,   SINGULAR, UINT32,   orig_size,         2) \
X(a, STATIC,   SINGULAR, UINT64,   team_id,           3) \
X(a, CALLBACK, SINGULAR, STRING,   hash,              4)
#define connect2_StartInlineDownloadCommand_CALLBACK pb_default_field_callback
#define connect2_StartInlineDownloadCommand_DEFAULT NULL

#define connect2_StartConnectDownloadCommand_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   path,              1) \
X(a, STATIC,   SINGULAR, UINT32,   orig_size,         2) \
X(a, STATIC,   SINGULAR, UINT64,   team_id,           3) \
X(a, CALLBACK, SINGULAR, STRING,   hash,              4)
#define connect2_StartConnectDownloadCommand_CALLBACK pb_default_field_callback
#define connect2_StartConnectDownloadCommand_DEFAULT NULL

#define connect2_StartEncryptedDownloadCommand_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   path,              1) \
X(a, STATIC,   SINGULAR, UINT32,   orig_size,         2) \
X(a, CALLBACK, SINGULAR, BYTES,    key,               3) \
X(a, CALLBACK, SINGULAR, BYTES,    iv,                4) \
X(a, STATIC,   SINGULAR, BOOL,     has_port,          5) \
X(a, STATIC,   SINGULAR, UINT32,   port,              6)
#define connect2_StartEncryptedDownloadCommand_CALLBACK pb_default_field_callback
#define connect2_StartEncryptedDownloadCommand_DEFAULT NULL

extern const pb_msgdesc_t connect2_CommandEnvelope_msg;
extern const pb_msgdesc_t connect2_SendInfoCommand_msg;
extern const pb_msgdesc_t connect2_SendJobInfoCommand_msg;
extern const pb_msgdesc_t connect2_SendFileInfoCommand_msg;
extern const pb_msgdesc_t connect2_SendTransferInfoCommand_msg;
extern const pb_msgdesc_t connect2_PausePrintCommand_msg;
extern const pb_msgdesc_t connect2_ResumePrintCommand_msg;
extern const pb_msgdesc_t connect2_StopPrintCommand_msg;
extern const pb_msgdesc_t connect2_ToolMappingPair_msg;
extern const pb_msgdesc_t connect2_StartPrintCommand_msg;
extern const pb_msgdesc_t connect2_SetPrinterReadyCommand_msg;
extern const pb_msgdesc_t connect2_CancelPrinterReadyCommand_msg;
extern const pb_msgdesc_t connect2_SetIdleCommand_msg;
extern const pb_msgdesc_t connect2_DeleteFileCommand_msg;
extern const pb_msgdesc_t connect2_DeleteFolderCommand_msg;
extern const pb_msgdesc_t connect2_CreateFolderCommand_msg;
extern const pb_msgdesc_t connect2_StopTransferCommand_msg;
extern const pb_msgdesc_t connect2_SetTokenCommand_msg;
extern const pb_msgdesc_t connect2_ResetPrinterCommand_msg;
extern const pb_msgdesc_t connect2_SendStateInfoCommand_msg;
extern const pb_msgdesc_t connect2_DialogActionCommand_msg;
extern const pb_msgdesc_t connect2_SetValueCommand_msg;
extern const pb_msgdesc_t connect2_CancelObjectCommand_msg;
extern const pb_msgdesc_t connect2_UncancelObjectCommand_msg;
extern const pb_msgdesc_t connect2_StartInlineDownloadCommand_msg;
extern const pb_msgdesc_t connect2_StartConnectDownloadCommand_msg;
extern const pb_msgdesc_t connect2_StartEncryptedDownloadCommand_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define connect2_CommandEnvelope_fields &connect2_CommandEnvelope_msg
#define connect2_SendInfoCommand_fields &connect2_SendInfoCommand_msg
#define connect2_SendJobInfoCommand_fields &connect2_SendJobInfoCommand_msg
#define connect2_SendFileInfoCommand_fields &connect2_SendFileInfoCommand_msg
#define connect2_SendTransferInfoCommand_fields &connect2_SendTransferInfoCommand_msg
#define connect2_PausePrintCommand_fields &connect2_PausePrintCommand_msg
#define connect2_ResumePrintCommand_fields &connect2_ResumePrintCommand_msg
#define connect2_StopPrintCommand_fields &connect2_StopPrintCommand_msg
#define connect2_ToolMappingPair_fields &connect2_ToolMappingPair_msg
#define connect2_StartPrintCommand_fields &connect2_StartPrintCommand_msg
#define connect2_SetPrinterReadyCommand_fields &connect2_SetPrinterReadyCommand_msg
#define connect2_CancelPrinterReadyCommand_fields &connect2_CancelPrinterReadyCommand_msg
#define connect2_SetIdleCommand_fields &connect2_SetIdleCommand_msg
#define connect2_DeleteFileCommand_fields &connect2_DeleteFileCommand_msg
#define connect2_DeleteFolderCommand_fields &connect2_DeleteFolderCommand_msg
#define connect2_CreateFolderCommand_fields &connect2_CreateFolderCommand_msg
#define connect2_StopTransferCommand_fields &connect2_StopTransferCommand_msg
#define connect2_SetTokenCommand_fields &connect2_SetTokenCommand_msg
#define connect2_ResetPrinterCommand_fields &connect2_ResetPrinterCommand_msg
#define connect2_SendStateInfoCommand_fields &connect2_SendStateInfoCommand_msg
#define connect2_DialogActionCommand_fields &connect2_DialogActionCommand_msg
#define connect2_SetValueCommand_fields &connect2_SetValueCommand_msg
#define connect2_CancelObjectCommand_fields &connect2_CancelObjectCommand_msg
#define connect2_UncancelObjectCommand_fields &connect2_UncancelObjectCommand_msg
#define connect2_StartInlineDownloadCommand_fields &connect2_StartInlineDownloadCommand_msg
#define connect2_StartConnectDownloadCommand_fields &connect2_StartConnectDownloadCommand_msg
#define connect2_StartEncryptedDownloadCommand_fields &connect2_StartEncryptedDownloadCommand_msg

/* Maximum encoded size of messages (where known) */
/* connect2_CommandEnvelope_size depends on runtime parameters */
/* connect2_SendFileInfoCommand_size depends on runtime parameters */
/* connect2_StartPrintCommand_size depends on runtime parameters */
/* connect2_DeleteFileCommand_size depends on runtime parameters */
/* connect2_DeleteFolderCommand_size depends on runtime parameters */
/* connect2_CreateFolderCommand_size depends on runtime parameters */
/* connect2_SetTokenCommand_size depends on runtime parameters */
/* connect2_SetValueCommand_size depends on runtime parameters */
/* connect2_StartInlineDownloadCommand_size depends on runtime parameters */
/* connect2_StartConnectDownloadCommand_size depends on runtime parameters */
/* connect2_StartEncryptedDownloadCommand_size depends on runtime parameters */
#define CONNECT2_COMMAND_PB_H_MAX_SIZE           connect2_ToolMappingPair_size
#define connect2_CancelObjectCommand_size        6
#define connect2_CancelPrinterReadyCommand_size  0
#define connect2_DialogActionCommand_size        8
#define connect2_PausePrintCommand_size          0
#define connect2_ResetPrinterCommand_size        2
#define connect2_ResumePrintCommand_size         0
#define connect2_SendInfoCommand_size            0
#define connect2_SendJobInfoCommand_size         8
#define connect2_SendStateInfoCommand_size       0
#define connect2_SendTransferInfoCommand_size    0
#define connect2_SetIdleCommand_size             0
#define connect2_SetPrinterReadyCommand_size     0
#define connect2_StopPrintCommand_size           0
#define connect2_StopTransferCommand_size        0
#define connect2_ToolMappingPair_size            12
#define connect2_UncancelObjectCommand_size      6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
