/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "command.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(connect2_CommandEnvelope, connect2_CommandEnvelope, AUTO)


PB_BIND(connect2_SendInfoCommand, connect2_SendInfoCommand, AUTO)


PB_BIND(connect2_SendJobInfoCommand, connect2_SendJobInfoCommand, AUTO)


PB_BIND(connect2_SendFileInfoCommand, connect2_SendFileInfoCommand, AUTO)


PB_BIND(connect2_SendTransferInfoCommand, connect2_SendTransferInfoCommand, AUTO)


PB_BIND(connect2_PausePrintCommand, connect2_PausePrintCommand, AUTO)


PB_BIND(connect2_ResumePrintCommand, connect2_ResumePrintCommand, AUTO)


PB_BIND(connect2_StopPrintCommand, connect2_StopPrintCommand, AUTO)


PB_BIND(connect2_ToolMappingPair, connect2_ToolMappingPair, AUTO)


PB_BIND(connect2_StartPrintCommand, connect2_StartPrintCommand, AUTO)


PB_BIND(connect2_SetPrinterReadyCommand, connect2_SetPrinterReadyCommand, AUTO)


PB_BIND(connect2_CancelPrinterReadyCommand, connect2_CancelPrinterReadyCommand, AUTO)


PB_BIND(connect2_SetIdleCommand, connect2_SetIdleCommand, AUTO)


PB_BIND(connect2_DeleteFileCommand, connect2_DeleteFileCommand, AUTO)


PB_BIND(connect2_DeleteFolderCommand, connect2_DeleteFolderCommand, AUTO)


PB_BIND(connect2_CreateFolderCommand, connect2_CreateFolderCommand, AUTO)


PB_BIND(connect2_StopTransferCommand, connect2_StopTransferCommand, AUTO)


PB_BIND(connect2_SetTokenCommand, connect2_SetTokenCommand, AUTO)


PB_BIND(connect2_ResetPrinterCommand, connect2_ResetPrinterCommand, AUTO)


PB_BIND(connect2_SendStateInfoCommand, connect2_SendStateInfoCommand, AUTO)


PB_BIND(connect2_DialogActionCommand, connect2_DialogActionCommand, AUTO)


PB_BIND(connect2_SetValueCommand, connect2_SetValueCommand, AUTO)


PB_BIND(connect2_CancelObjectCommand, connect2_CancelObjectCommand, AUTO)


PB_BIND(connect2_UncancelObjectCommand, connect2_UncancelObjectCommand, AUTO)


PB_BIND(connect2_StartInlineDownloadCommand, connect2_StartInlineDownloadCommand, AUTO)


PB_BIND(connect2_StartConnectDownloadCommand, connect2_StartConnectDownloadCommand, AUTO)


PB_BIND(connect2_StartEncryptedDownloadCommand, connect2_StartEncryptedDownloadCommand, AUTO)







