/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_CONNECT2_EVENT_PB_H_INCLUDED
#define PB_CONNECT2_EVENT_PB_H_INCLUDED
#include <pb.h>
#include "command.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Shared machine-readable reason values found in old planner/render code. */
typedef enum _connect2_MachineReason {
    connect2_MachineReason_MACHINE_REASON_UNSPECIFIED = 0,
    connect2_MachineReason_MACHINE_REASON_TRANSFER_IN_PROGRESS = 1,
    connect2_MachineReason_MACHINE_REASON_FILE_EXISTS = 2,
    connect2_MachineReason_MACHINE_REASON_STORAGE_FAILURE = 3,
    connect2_MachineReason_MACHINE_REASON_NETWORK_FAILURE = 4,
    connect2_MachineReason_MACHINE_REASON_NOT_READY = 5
} connect2_MachineReason;

typedef enum _connect2_EventType {
    connect2_EventType_EVENT_TYPE_UNSPECIFIED = 0,
    connect2_EventType_EVENT_TYPE_INFO = 1,
    connect2_EventType_EVENT_TYPE_ACCEPTED = 2,
    connect2_EventType_EVENT_TYPE_REJECTED = 3,
    connect2_EventType_EVENT_TYPE_JOB_INFO = 4,
    connect2_EventType_EVENT_TYPE_FILE_INFO = 5,
    connect2_EventType_EVENT_TYPE_FILE_CHANGED = 6,
    connect2_EventType_EVENT_TYPE_TRANSFER_INFO = 7,
    connect2_EventType_EVENT_TYPE_FINISHED = 8,
    connect2_EventType_EVENT_TYPE_FAILED = 9,
    connect2_EventType_EVENT_TYPE_TRANSFER_STOPPED = 10,
    connect2_EventType_EVENT_TYPE_TRANSFER_ABORTED = 11,
    connect2_EventType_EVENT_TYPE_TRANSFER_FINISHED = 12,
    connect2_EventType_EVENT_TYPE_CANCELABLE_CHANGED = 13,
    connect2_EventType_EVENT_TYPE_STATE_CHANGED = 14
} connect2_EventType;

/* Transfer type values historically rendered by old transfer code. */
typedef enum _connect2_TransferType {
    connect2_TransferType_TRANSFER_TYPE_UNSPECIFIED = 0,
    connect2_TransferType_TRANSFER_TYPE_NO_TRANSFER = 1,
    connect2_TransferType_TRANSFER_TYPE_CONNECT = 2,
    connect2_TransferType_TRANSFER_TYPE_LINK = 3
} connect2_TransferType;

/* Struct definitions */
typedef struct _connect2_StorageInfo {
    /* Legacy JSON key: data.storages[].mountpoint */
    pb_callback_t mountpoint;
    /* Legacy JSON key: data.storages[].type */
    pb_callback_t type;
    /* Legacy JSON key: data.storages[].read_only */
    bool read_only;
    /* Legacy JSON key: data.storages[].free_space */
    uint64_t free_space;
    /* Legacy JSON key: data.storages[].is_sfn */
    bool is_sfn;
} connect2_StorageInfo;

typedef struct _connect2_NetworkInfo {
    pb_callback_t lan_mac;
    pb_callback_t lan_ipv4;
    pb_callback_t wifi_ssid;
    pb_callback_t wifi_mac;
    pb_callback_t wifi_ipv4;
    pb_callback_t hostname;
} connect2_NetworkInfo;

typedef struct _connect2_ToolInfo {
    uint32_t slot;
    float nozzle_diameter;
    bool high_flow;
    bool hardened;
    pb_callback_t material;
} connect2_ToolInfo;

typedef struct _connect2_EnclosureInfo {
    bool enabled;
    bool printing_filtration;
    bool post_print;
    uint32_t post_print_filtration_time;
    uint32_t filter_lifetime;
    pb_callback_t filtration_filaments;
} connect2_EnclosureInfo;

typedef struct _connect2_MmuInfo {
    bool enabled;
    pb_callback_t version;
} connect2_MmuInfo;

/* Replaces legacy JSON event:
 {
   "event": "INFO",
   "state": "...",
   "dialog_id": ...,
   "command_id": ...,
   "data": {
     "firmware": "...",
     "printer_type": "...",
     "sn": "...",
     "appendix": false,
     "fingerprint": "...",
     "nozzle_diameter": 0.4,
     "transfer_paused": false,
     "api_key": "...",
     "storages": [...],
     "network_info": {...},
     "tools": [...],
     "enclosure": {...},
     "mmu": {...},
     "addon_power": false,
     "slots": 1
   }
 }

 Purpose:
 Full printer information snapshot. */
typedef struct _connect2_InfoPayload {
    pb_callback_t firmware;
    pb_callback_t printer_type;
    pb_callback_t sn;
    bool appendix;
    pb_callback_t fingerprint;
    float nozzle_diameter;
    bool transfer_paused;
    /* Legacy JSON key: data.api_key
 Historically derived from net creds in old code. */
    pb_callback_t api_key;
    pb_callback_t storages;
    bool has_network_info;
    connect2_NetworkInfo network_info;
    pb_callback_t tools;
    bool has_enclosure;
    connect2_EnclosureInfo enclosure;
    bool has_mmu;
    connect2_MmuInfo mmu;
    bool addon_power;
    uint32_t slots;
} connect2_InfoPayload;

/* Replaces legacy JSON event:
 {
   "event": "ACCEPTED",
   "state": "...",
   "command_id": ...
 }

 Purpose:
 Positive acknowledgement for commands that historically used ACCEPTED rather
 than FINISHED. */
typedef struct _connect2_AcceptedPayload {
    char dummy_field;
} connect2_AcceptedPayload;

/* Replaces legacy JSON event:
 {
   "event": "REJECTED",
   "state": "...",
   "command_id": ...,
   "reason": "..."
 }
 or, depending on rendering path, reason effectively appeared inside data-like
 handling associated with the event. */
typedef struct _connect2_RejectedPayload {
    pb_callback_t reason;
} connect2_RejectedPayload;

/* Replaces legacy JSON event:
 {
   "event": "JOB_INFO",
   "state": "PRINTING",
   "dialog_id": ...,
   "command_id": ...,
   "job_id": 123,
   "data": {
     "state": "PRINTING",
     "size": 123456,
     "m_timestamp": 1700000000,
     "display_name": "Part.gcode",
     "start_cmd_id": 42,
     "path": "/usb/PART.GCO"
   }
 } */
typedef struct _connect2_JobInfoPayload {
    bool has_job_id;
    uint32_t job_id;
    pb_callback_t state;
    uint64_t size;
    uint64_t m_timestamp;
    pb_callback_t display_name;
    uint32_t start_cmd_id;
    pb_callback_t path;
} connect2_JobInfoPayload;

/* Shared metadata describing a filesystem entry. */
typedef struct _connect2_FileEntry {
    /* Legacy JSON key: name */
    pb_callback_t name;
    /* Legacy JSON key: display_name */
    pb_callback_t display_name;
    /* Legacy JSON key: size */
    uint64_t size;
    /* Legacy JSON key: m_timestamp */
    uint64_t m_timestamp;
    /* Legacy JSON key: read_only */
    bool read_only;
    /* Legacy JSON key: type */
    pb_callback_t type;
} connect2_FileEntry;

/* Replaces legacy JSON event:
 {
   "event": "FILE_INFO",
   "state": "...",
   "command_id": ...,
   "data": {
     "path": "/usb/...",
     "display_name": "...",
     "type": "FILE|FOLDER|...",
     "size": 123,
     "m_timestamp": 1700000000,
     "read_only": false,
     "children": [...],
     "file_count": 12
   }
 }

 Important legacy behavior:
 - when target was a directory, children could be streamed in JSON because the
   old renderer was segmented
 - constrained protobuf implementation may need paging or capped child count */
typedef struct _connect2_FileInfoPayload {
    pb_callback_t path;
    pb_callback_t display_name;
    pb_callback_t type;
    uint64_t size;
    uint64_t m_timestamp;
    bool read_only;
    pb_callback_t children;
    uint32_t file_count;
} connect2_FileInfoPayload;

/* Replaces legacy JSON event:
 {
   "event": "FILE_CHANGED",
   "state": "...",
   "command_id": ...,
   "data": {
     "free_space": 123456,
     "new_path": "/usb/new.gcode",
     "old_path": "/usb/old.gcode",
     "rescan": true,
     "file": {
       "size": 123,
       "m_timestamp": 1700000000,
       "type": "FILE|FOLDER",
       "name": "NEW.GCO"
     }
   }
 } */
typedef struct _connect2_FileChangedPayload {
    uint64_t free_space;
    pb_callback_t new_path;
    pb_callback_t old_path;
    bool rescan;
    bool has_file;
    connect2_FileEntry file;
} connect2_FileChangedPayload;

/* Replaces legacy JSON event:
 {
   "event": "TRANSFER_INFO",
   "state": "...",
   "command_id": ...,
   "data": {
     "size": 123456,
     "transferred": 1000,
     "progress": 1.2,
     "time_remaining": 999,
     "time_transferring": 10,
     "path": "/usb/file.gcode",
     "start_cmd_id": 42,
     "type": "CONNECT|LINK|NO_TRANSFER"
   }
 } */
typedef struct _connect2_TransferInfoPayload {
    uint64_t size;
    uint64_t transferred;
    float progress;
    uint32_t time_remaining;
    uint32_t time_transferring;
    pb_callback_t path;
    bool has_start_cmd_id;
    uint32_t start_cmd_id;
    connect2_TransferType type;
} connect2_TransferInfoPayload;

/* Replaces legacy JSON event:
 {
   "event": "FINISHED",
   "state": "...",
   "command_id": ...
 } */
typedef struct _connect2_FinishedPayload {
    char dummy_field;
} connect2_FinishedPayload;

/* Replaces legacy JSON event:
 {
   "event": "FAILED",
   "state": "...",
   "command_id": ...,
   "reason": "..."
 } */
typedef struct _connect2_FailedPayload {
    pb_callback_t reason;
} connect2_FailedPayload;

/* Replaces legacy JSON event:
 {
   "event": "TRANSFER_STOPPED",
   "state": "...",
   "command_id": ...,
   "data": {
     "start_cmd_id": 42
   }
 } */
typedef struct _connect2_TransferStoppedPayload {
    bool has_start_cmd_id;
    uint32_t start_cmd_id;
} connect2_TransferStoppedPayload;

/* Replaces legacy JSON event:
 {
   "event": "TRANSFER_ABORTED",
   "state": "...",
   "command_id": ...,
   "data": {
     "start_cmd_id": 42
   },
   "machine_reason": "STORAGE_FAILURE|NETWORK_FAILURE|..."
 } */
typedef struct _connect2_TransferAbortedPayload {
    bool has_start_cmd_id;
    uint32_t start_cmd_id;
} connect2_TransferAbortedPayload;

/* Replaces legacy JSON event:
 {
   "event": "TRANSFER_FINISHED",
   "state": "...",
   "command_id": ...,
   "data": {
     "start_cmd_id": 42
   }
 } */
typedef struct _connect2_TransferFinishedPayload {
    bool has_start_cmd_id;
    uint32_t start_cmd_id;
} connect2_TransferFinishedPayload;

/* Replaces legacy JSON event:
 {
   "event": "CANCELABLE_CHANGED",
   "state": "...",
   "data": {
     "objects": [
       { "canceled": false, "id": 0 },
       { "canceled": true, "id": 1 }
     ]
   }
 } */
typedef struct _connect2_CancelableObject {
    uint32_t id;
    bool canceled;
} connect2_CancelableObject;

typedef struct _connect2_CancelableChangedPayload {
    pb_callback_t objects;
} connect2_CancelableChangedPayload;

/* Replaces legacy JSON event:
 {
   "event": "STATE_CHANGED",
   "state": "...",
   "dialog_id": ...,
   "command_id": ...,
   "data": {
     "code": "12345",
     "title": "...",
     "text": "...",
     "buttons": ["YES", "NO"]
   }
 }

 Legacy behavior:
 - data object was sparse, fields were emitted only when present
 - event frequency was based on a state fingerprint, not only visible state */
typedef struct _connect2_StateChangedPayload {
    bool has_code;
    pb_callback_t code;
    bool has_title;
    pb_callback_t title;
    bool has_text;
    pb_callback_t text;
    pb_callback_t buttons;
} connect2_StateChangedPayload;

/* Top-level event envelope emitted from printer to proxy over MQTT. */
typedef struct _connect2_EventEnvelope {
    /* Legacy JSON top-level key: event */
    connect2_EventType event;
    /* Legacy JSON top-level key: state */
    pb_callback_t state;
    /* True when legacy JSON included top-level dialog_id. */
    bool has_dialog_id;
    uint32_t dialog_id;
    /* True when the event is associated with a command response and old JSON
 included top-level command_id. */
    bool has_command_id;
    uint32_t command_id;
    /* True when old JSON included top-level transfer_id. */
    bool has_transfer_id;
    uint32_t transfer_id;
    /* Human-readable reason string. Historically this was used mainly by
 REJECTED and some failure-like cases. */
    bool has_reason;
    pb_callback_t reason;
    /* Machine-readable reason enum from old planner Event.machine_reason. */
    connect2_MachineReason machine_reason;
    pb_size_t which_payload;
    union {
        connect2_InfoPayload info;
        connect2_AcceptedPayload accepted;
        connect2_RejectedPayload rejected;
        connect2_JobInfoPayload job_info;
        connect2_FileInfoPayload file_info;
        connect2_FileChangedPayload file_changed;
        connect2_TransferInfoPayload transfer_info;
        connect2_FinishedPayload finished;
        connect2_FailedPayload failed;
        connect2_TransferStoppedPayload transfer_stopped;
        connect2_TransferAbortedPayload transfer_aborted;
        connect2_TransferFinishedPayload transfer_finished;
        connect2_CancelableChangedPayload cancelable_changed;
        connect2_StateChangedPayload state_changed;
    } payload;
} connect2_EventEnvelope;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _connect2_MachineReason_MIN connect2_MachineReason_MACHINE_REASON_UNSPECIFIED
#define _connect2_MachineReason_MAX connect2_MachineReason_MACHINE_REASON_NOT_READY
#define _connect2_MachineReason_ARRAYSIZE ((connect2_MachineReason)(connect2_MachineReason_MACHINE_REASON_NOT_READY+1))

#define _connect2_EventType_MIN connect2_EventType_EVENT_TYPE_UNSPECIFIED
#define _connect2_EventType_MAX connect2_EventType_EVENT_TYPE_STATE_CHANGED
#define _connect2_EventType_ARRAYSIZE ((connect2_EventType)(connect2_EventType_EVENT_TYPE_STATE_CHANGED+1))

#define _connect2_TransferType_MIN connect2_TransferType_TRANSFER_TYPE_UNSPECIFIED
#define _connect2_TransferType_MAX connect2_TransferType_TRANSFER_TYPE_LINK
#define _connect2_TransferType_ARRAYSIZE ((connect2_TransferType)(connect2_TransferType_TRANSFER_TYPE_LINK+1))

#define connect2_EventEnvelope_event_ENUMTYPE connect2_EventType
#define connect2_EventEnvelope_machine_reason_ENUMTYPE connect2_MachineReason













#define connect2_TransferInfoPayload_type_ENUMTYPE connect2_TransferType








#define connect2_StateChangedPayload_buttons_ENUMTYPE connect2_DialogButton


/* Initializer values for message structs */
#define connect2_EventEnvelope_init_default      {_connect2_EventType_MIN, {{NULL}, NULL}, 0, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}, _connect2_MachineReason_MIN, 0, {connect2_InfoPayload_init_default}}
#define connect2_InfoPayload_init_default        {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, connect2_NetworkInfo_init_default, {{NULL}, NULL}, false, connect2_EnclosureInfo_init_default, false, connect2_MmuInfo_init_default, 0, 0}
#define connect2_StorageInfo_init_default        {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0}
#define connect2_NetworkInfo_init_default        {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define connect2_ToolInfo_init_default           {0, 0, 0, 0, {{NULL}, NULL}}
#define connect2_EnclosureInfo_init_default      {0, 0, 0, 0, 0, {{NULL}, NULL}}
#define connect2_MmuInfo_init_default            {0, {{NULL}, NULL}}
#define connect2_AcceptedPayload_init_default    {0}
#define connect2_RejectedPayload_init_default    {{{NULL}, NULL}}
#define connect2_JobInfoPayload_init_default     {0, 0, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define connect2_FileEntry_init_default          {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}}
#define connect2_FileInfoPayload_init_default    {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}, 0}
#define connect2_FileChangedPayload_init_default {0, {{NULL}, NULL}, {{NULL}, NULL}, 0, false, connect2_FileEntry_init_default}
#define connect2_TransferInfoPayload_init_default {0, 0, 0, 0, 0, {{NULL}, NULL}, 0, 0, _connect2_TransferType_MIN}
#define connect2_FinishedPayload_init_default    {0}
#define connect2_FailedPayload_init_default      {{{NULL}, NULL}}
#define connect2_TransferStoppedPayload_init_default {0, 0}
#define connect2_TransferAbortedPayload_init_default {0, 0}
#define connect2_TransferFinishedPayload_init_default {0, 0}
#define connect2_CancelableObject_init_default   {0, 0}
#define connect2_CancelableChangedPayload_init_default {{{NULL}, NULL}}
#define connect2_StateChangedPayload_init_default {0, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define connect2_EventEnvelope_init_zero         {_connect2_EventType_MIN, {{NULL}, NULL}, 0, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}, _connect2_MachineReason_MIN, 0, {connect2_InfoPayload_init_zero}}
#define connect2_InfoPayload_init_zero           {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, connect2_NetworkInfo_init_zero, {{NULL}, NULL}, false, connect2_EnclosureInfo_init_zero, false, connect2_MmuInfo_init_zero, 0, 0}
#define connect2_StorageInfo_init_zero           {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0}
#define connect2_NetworkInfo_init_zero           {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define connect2_ToolInfo_init_zero              {0, 0, 0, 0, {{NULL}, NULL}}
#define connect2_EnclosureInfo_init_zero         {0, 0, 0, 0, 0, {{NULL}, NULL}}
#define connect2_MmuInfo_init_zero               {0, {{NULL}, NULL}}
#define connect2_AcceptedPayload_init_zero       {0}
#define connect2_RejectedPayload_init_zero       {{{NULL}, NULL}}
#define connect2_JobInfoPayload_init_zero        {0, 0, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define connect2_FileEntry_init_zero             {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}}
#define connect2_FileInfoPayload_init_zero       {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}, 0}
#define connect2_FileChangedPayload_init_zero    {0, {{NULL}, NULL}, {{NULL}, NULL}, 0, false, connect2_FileEntry_init_zero}
#define connect2_TransferInfoPayload_init_zero   {0, 0, 0, 0, 0, {{NULL}, NULL}, 0, 0, _connect2_TransferType_MIN}
#define connect2_FinishedPayload_init_zero       {0}
#define connect2_FailedPayload_init_zero         {{{NULL}, NULL}}
#define connect2_TransferStoppedPayload_init_zero {0, 0}
#define connect2_TransferAbortedPayload_init_zero {0, 0}
#define connect2_TransferFinishedPayload_init_zero {0, 0}
#define connect2_CancelableObject_init_zero      {0, 0}
#define connect2_CancelableChangedPayload_init_zero {{{NULL}, NULL}}
#define connect2_StateChangedPayload_init_zero   {0, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define connect2_StorageInfo_mountpoint_tag      1
#define connect2_StorageInfo_type_tag            2
#define connect2_StorageInfo_read_only_tag       3
#define connect2_StorageInfo_free_space_tag      4
#define connect2_StorageInfo_is_sfn_tag          5
#define connect2_NetworkInfo_lan_mac_tag         1
#define connect2_NetworkInfo_lan_ipv4_tag        2
#define connect2_NetworkInfo_wifi_ssid_tag       3
#define connect2_NetworkInfo_wifi_mac_tag        4
#define connect2_NetworkInfo_wifi_ipv4_tag       5
#define connect2_NetworkInfo_hostname_tag        6
#define connect2_ToolInfo_slot_tag               1
#define connect2_ToolInfo_nozzle_diameter_tag    2
#define connect2_ToolInfo_high_flow_tag          3
#define connect2_ToolInfo_hardened_tag           4
#define connect2_ToolInfo_material_tag           5
#define connect2_EnclosureInfo_enabled_tag       1
#define connect2_EnclosureInfo_printing_filtration_tag 2
#define connect2_EnclosureInfo_post_print_tag    3
#define connect2_EnclosureInfo_post_print_filtration_time_tag 4
#define connect2_EnclosureInfo_filter_lifetime_tag 5
#define connect2_EnclosureInfo_filtration_filaments_tag 6
#define connect2_MmuInfo_enabled_tag             1
#define connect2_MmuInfo_version_tag             2
#define connect2_InfoPayload_firmware_tag        1
#define connect2_InfoPayload_printer_type_tag    2
#define connect2_InfoPayload_sn_tag              3
#define connect2_InfoPayload_appendix_tag        4
#define connect2_InfoPayload_fingerprint_tag     5
#define connect2_InfoPayload_nozzle_diameter_tag 6
#define connect2_InfoPayload_transfer_paused_tag 7
#define connect2_InfoPayload_api_key_tag         8
#define connect2_InfoPayload_storages_tag        9
#define connect2_InfoPayload_network_info_tag    10
#define connect2_InfoPayload_tools_tag           11
#define connect2_InfoPayload_enclosure_tag       12
#define connect2_InfoPayload_mmu_tag             13
#define connect2_InfoPayload_addon_power_tag     14
#define connect2_InfoPayload_slots_tag           15
#define connect2_RejectedPayload_reason_tag      1
#define connect2_JobInfoPayload_has_job_id_tag   1
#define connect2_JobInfoPayload_job_id_tag       2
#define connect2_JobInfoPayload_state_tag        3
#define connect2_JobInfoPayload_size_tag         4
#define connect2_JobInfoPayload_m_timestamp_tag  5
#define connect2_JobInfoPayload_display_name_tag 6
#define connect2_JobInfoPayload_start_cmd_id_tag 7
#define connect2_JobInfoPayload_path_tag         8
#define connect2_FileEntry_name_tag              1
#define connect2_FileEntry_display_name_tag      2
#define connect2_FileEntry_size_tag              3
#define connect2_FileEntry_m_timestamp_tag       4
#define connect2_FileEntry_read_only_tag         5
#define connect2_FileEntry_type_tag              6
#define connect2_FileInfoPayload_path_tag        1
#define connect2_FileInfoPayload_display_name_tag 2
#define connect2_FileInfoPayload_type_tag        3
#define connect2_FileInfoPayload_size_tag        4
#define connect2_FileInfoPayload_m_timestamp_tag 5
#define connect2_FileInfoPayload_read_only_tag   6
#define connect2_FileInfoPayload_children_tag    7
#define connect2_FileInfoPayload_file_count_tag  8
#define connect2_FileChangedPayload_free_space_tag 1
#define connect2_FileChangedPayload_new_path_tag 2
#define connect2_FileChangedPayload_old_path_tag 3
#define connect2_FileChangedPayload_rescan_tag   4
#define connect2_FileChangedPayload_file_tag     5
#define connect2_TransferInfoPayload_size_tag    1
#define connect2_TransferInfoPayload_transferred_tag 2
#define connect2_TransferInfoPayload_progress_tag 3
#define connect2_TransferInfoPayload_time_remaining_tag 4
#define connect2_TransferInfoPayload_time_transferring_tag 5
#define connect2_TransferInfoPayload_path_tag    6
#define connect2_TransferInfoPayload_has_start_cmd_id_tag 7
#define connect2_TransferInfoPayload_start_cmd_id_tag 8
#define connect2_TransferInfoPayload_type_tag    9
#define connect2_FailedPayload_reason_tag        1
#define connect2_TransferStoppedPayload_has_start_cmd_id_tag 1
#define connect2_TransferStoppedPayload_start_cmd_id_tag 2
#define connect2_TransferAbortedPayload_has_start_cmd_id_tag 1
#define connect2_TransferAbortedPayload_start_cmd_id_tag 2
#define connect2_TransferFinishedPayload_has_start_cmd_id_tag 1
#define connect2_TransferFinishedPayload_start_cmd_id_tag 2
#define connect2_CancelableObject_id_tag         1
#define connect2_CancelableObject_canceled_tag   2
#define connect2_CancelableChangedPayload_objects_tag 1
#define connect2_StateChangedPayload_has_code_tag 1
#define connect2_StateChangedPayload_code_tag    2
#define connect2_StateChangedPayload_has_title_tag 3
#define connect2_StateChangedPayload_title_tag   4
#define connect2_StateChangedPayload_has_text_tag 5
#define connect2_StateChangedPayload_text_tag    6
#define connect2_StateChangedPayload_buttons_tag 7
#define connect2_EventEnvelope_event_tag         1
#define connect2_EventEnvelope_state_tag         2
#define connect2_EventEnvelope_has_dialog_id_tag 3
#define connect2_EventEnvelope_dialog_id_tag     4
#define connect2_EventEnvelope_has_command_id_tag 5
#define connect2_EventEnvelope_command_id_tag    6
#define connect2_EventEnvelope_has_transfer_id_tag 7
#define connect2_EventEnvelope_transfer_id_tag   8
#define connect2_EventEnvelope_has_reason_tag    9
#define connect2_EventEnvelope_reason_tag        10
#define connect2_EventEnvelope_machine_reason_tag 11
#define connect2_EventEnvelope_info_tag          20
#define connect2_EventEnvelope_accepted_tag      21
#define connect2_EventEnvelope_rejected_tag      22
#define connect2_EventEnvelope_job_info_tag      23
#define connect2_EventEnvelope_file_info_tag     24
#define connect2_EventEnvelope_file_changed_tag  25
#define connect2_EventEnvelope_transfer_info_tag 26
#define connect2_EventEnvelope_finished_tag      27
#define connect2_EventEnvelope_failed_tag        28
#define connect2_EventEnvelope_transfer_stopped_tag 29
#define connect2_EventEnvelope_transfer_aborted_tag 30
#define connect2_EventEnvelope_transfer_finished_tag 31
#define connect2_EventEnvelope_cancelable_changed_tag 32
#define connect2_EventEnvelope_state_changed_tag 33

/* Struct field encoding specification for nanopb */
#define connect2_EventEnvelope_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    event,             1) \
X(a, CALLBACK, SINGULAR, STRING,   state,             2) \
X(a, STATIC,   SINGULAR, BOOL,     has_dialog_id,     3) \
X(a, STATIC,   SINGULAR, UINT32,   dialog_id,         4) \
X(a, STATIC,   SINGULAR, BOOL,     has_command_id,    5) \
X(a, STATIC,   SINGULAR, UINT32,   command_id,        6) \
X(a, STATIC,   SINGULAR, BOOL,     has_transfer_id,   7) \
X(a, STATIC,   SINGULAR, UINT32,   transfer_id,       8) \
X(a, STATIC,   SINGULAR, BOOL,     has_reason,        9) \
X(a, CALLBACK, SINGULAR, STRING,   reason,           10) \
X(a, STATIC,   SINGULAR, UENUM,    machine_reason,   11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,info,payload.info),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,accepted,payload.accepted),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,rejected,payload.rejected),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,job_info,payload.job_info),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,file_info,payload.file_info),  24) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,file_changed,payload.file_changed),  25) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,transfer_info,payload.transfer_info),  26) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,finished,payload.finished),  27) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,failed,payload.failed),  28) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,transfer_stopped,payload.transfer_stopped),  29) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,transfer_aborted,payload.transfer_aborted),  30) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,transfer_finished,payload.transfer_finished),  31) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,cancelable_changed,payload.cancelable_changed),  32) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,state_changed,payload.state_changed),  33)
#define connect2_EventEnvelope_CALLBACK pb_default_field_callback
#define connect2_EventEnvelope_DEFAULT NULL
#define connect2_EventEnvelope_payload_info_MSGTYPE connect2_InfoPayload
#define connect2_EventEnvelope_payload_accepted_MSGTYPE connect2_AcceptedPayload
#define connect2_EventEnvelope_payload_rejected_MSGTYPE connect2_RejectedPayload
#define connect2_EventEnvelope_payload_job_info_MSGTYPE connect2_JobInfoPayload
#define connect2_EventEnvelope_payload_file_info_MSGTYPE connect2_FileInfoPayload
#define connect2_EventEnvelope_payload_file_changed_MSGTYPE connect2_FileChangedPayload
#define connect2_EventEnvelope_payload_transfer_info_MSGTYPE connect2_TransferInfoPayload
#define connect2_EventEnvelope_payload_finished_MSGTYPE connect2_FinishedPayload
#define connect2_EventEnvelope_payload_failed_MSGTYPE connect2_FailedPayload
#define connect2_EventEnvelope_payload_transfer_stopped_MSGTYPE connect2_TransferStoppedPayload
#define connect2_EventEnvelope_payload_transfer_aborted_MSGTYPE connect2_TransferAbortedPayload
#define connect2_EventEnvelope_payload_transfer_finished_MSGTYPE connect2_TransferFinishedPayload
#define connect2_EventEnvelope_payload_cancelable_changed_MSGTYPE connect2_CancelableChangedPayload
#define connect2_EventEnvelope_payload_state_changed_MSGTYPE connect2_StateChangedPayload

#define connect2_InfoPayload_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   firmware,          1) \
X(a, CALLBACK, SINGULAR, STRING,   printer_type,      2) \
X(a, CALLBACK, SINGULAR, STRING,   sn,                3) \
X(a, STATIC,   SINGULAR, BOOL,     appendix,          4) \
X(a, CALLBACK, SINGULAR, STRING,   fingerprint,       5) \
X(a, STATIC,   SINGULAR, FLOAT,    nozzle_diameter,   6) \
X(a, STATIC,   SINGULAR, BOOL,     transfer_paused,   7) \
X(a, CALLBACK, SINGULAR, STRING,   api_key,           8) \
X(a, CALLBACK, REPEATED, MESSAGE,  storages,          9) \
X(a, STATIC,   OPTIONAL, MESSAGE,  network_info,     10) \
X(a, CALLBACK, REPEATED, MESSAGE,  tools,            11) \
X(a, STATIC,   OPTIONAL, MESSAGE,  enclosure,        12) \
X(a, STATIC,   OPTIONAL, MESSAGE,  mmu,              13) \
X(a, STATIC,   SINGULAR, BOOL,     addon_power,      14) \
X(a, STATIC,   SINGULAR, UINT32,   slots,            15)
#define connect2_InfoPayload_CALLBACK pb_default_field_callback
#define connect2_InfoPayload_DEFAULT NULL
#define connect2_InfoPayload_storages_MSGTYPE connect2_StorageInfo
#define connect2_InfoPayload_network_info_MSGTYPE connect2_NetworkInfo
#define connect2_InfoPayload_tools_MSGTYPE connect2_ToolInfo
#define connect2_InfoPayload_enclosure_MSGTYPE connect2_EnclosureInfo
#define connect2_InfoPayload_mmu_MSGTYPE connect2_MmuInfo

#define connect2_StorageInfo_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   mountpoint,        1) \
X(a, CALLBACK, SINGULAR, STRING,   type,              2) \
X(a, STATIC,   SINGULAR, BOOL,     read_only,         3) \
X(a, STATIC,   SINGULAR, UINT64,   free_space,        4) \
X(a, STATIC,   SINGULAR, BOOL,     is_sfn,            5)
#define connect2_StorageInfo_CALLBACK pb_default_field_callback
#define connect2_StorageInfo_DEFAULT NULL

#define connect2_NetworkInfo_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   lan_mac,           1) \
X(a, CALLBACK, SINGULAR, STRING,   lan_ipv4,          2) \
X(a, CALLBACK, SINGULAR, STRING,   wifi_ssid,         3) \
X(a, CALLBACK, SINGULAR, STRING,   wifi_mac,          4) \
X(a, CALLBACK, SINGULAR, STRING,   wifi_ipv4,         5) \
X(a, CALLBACK, SINGULAR, STRING,   hostname,          6)
#define connect2_NetworkInfo_CALLBACK pb_default_field_callback
#define connect2_NetworkInfo_DEFAULT NULL

#define connect2_ToolInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   slot,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    nozzle_diameter,   2) \
X(a, STATIC,   SINGULAR, BOOL,     high_flow,         3) \
X(a, STATIC,   SINGULAR, BOOL,     hardened,          4) \
X(a, CALLBACK, SINGULAR, STRING,   material,          5)
#define connect2_ToolInfo_CALLBACK pb_default_field_callback
#define connect2_ToolInfo_DEFAULT NULL

#define connect2_EnclosureInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           1) \
X(a, STATIC,   SINGULAR, BOOL,     printing_filtration,   2) \
X(a, STATIC,   SINGULAR, BOOL,     post_print,        3) \
X(a, STATIC,   SINGULAR, UINT32,   post_print_filtration_time,   4) \
X(a, STATIC,   SINGULAR, UINT32,   filter_lifetime,   5) \
X(a, CALLBACK, REPEATED, STRING,   filtration_filaments,   6)
#define connect2_EnclosureInfo_CALLBACK pb_default_field_callback
#define connect2_EnclosureInfo_DEFAULT NULL

#define connect2_MmuInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           1) \
X(a, CALLBACK, SINGULAR, STRING,   version,           2)
#define connect2_MmuInfo_CALLBACK pb_default_field_callback
#define connect2_MmuInfo_DEFAULT NULL

#define connect2_AcceptedPayload_FIELDLIST(X, a) \

#define connect2_AcceptedPayload_CALLBACK NULL
#define connect2_AcceptedPayload_DEFAULT NULL

#define connect2_RejectedPayload_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   reason,            1)
#define connect2_RejectedPayload_CALLBACK pb_default_field_callback
#define connect2_RejectedPayload_DEFAULT NULL

#define connect2_JobInfoPayload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     has_job_id,        1) \
X(a, STATIC,   SINGULAR, UINT32,   job_id,            2) \
X(a, CALLBACK, SINGULAR, STRING,   state,             3) \
X(a, STATIC,   SINGULAR, UINT64,   size,              4) \
X(a, STATIC,   SINGULAR, UINT64,   m_timestamp,       5) \
X(a, CALLBACK, SINGULAR, STRING,   display_name,      6) \
X(a, STATIC,   SINGULAR, UINT32,   start_cmd_id,      7) \
X(a, CALLBACK, SINGULAR, STRING,   path,              8)
#define connect2_JobInfoPayload_CALLBACK pb_default_field_callback
#define connect2_JobInfoPayload_DEFAULT NULL

#define connect2_FileEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, SINGULAR, STRING,   display_name,      2) \
X(a, STATIC,   SINGULAR, UINT64,   size,              3) \
X(a, STATIC,   SINGULAR, UINT64,   m_timestamp,       4) \
X(a, STATIC,   SINGULAR, BOOL,     read_only,         5) \
X(a, CALLBACK, SINGULAR, STRING,   type,              6)
#define connect2_FileEntry_CALLBACK pb_default_field_callback
#define connect2_FileEntry_DEFAULT NULL

#define connect2_FileInfoPayload_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   path,              1) \
X(a, CALLBACK, SINGULAR, STRING,   display_name,      2) \
X(a, CALLBACK, SINGULAR, STRING,   type,              3) \
X(a, STATIC,   SINGULAR, UINT64,   size,              4) \
X(a, STATIC,   SINGULAR, UINT64,   m_timestamp,       5) \
X(a, STATIC,   SINGULAR, BOOL,     read_only,         6) \
X(a, CALLBACK, REPEATED, MESSAGE,  children,          7) \
X(a, STATIC,   SINGULAR, UINT32,   file_count,        8)
#define connect2_FileInfoPayload_CALLBACK pb_default_field_callback
#define connect2_FileInfoPayload_DEFAULT NULL
#define connect2_FileInfoPayload_children_MSGTYPE connect2_FileEntry

#define connect2_FileChangedPayload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   free_space,        1) \
X(a, CALLBACK, SINGULAR, STRING,   new_path,          2) \
X(a, CALLBACK, SINGULAR, STRING,   old_path,          3) \
X(a, STATIC,   SINGULAR, BOOL,     rescan,            4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  file,              5)
#define connect2_FileChangedPayload_CALLBACK pb_default_field_callback
#define connect2_FileChangedPayload_DEFAULT NULL
#define connect2_FileChangedPayload_file_MSGTYPE connect2_FileEntry

#define connect2_TransferInfoPayload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   size,              1) \
X(a, STATIC,   SINGULAR, UINT64,   transferred,       2) \
X(a, STATIC,   SINGULAR, FLOAT,    progress,          3) \
X(a, STATIC,   SINGULAR, UINT32,   time_remaining,    4) \
X(a, STATIC,   SINGULAR, UINT32,   time_transferring,   5) \
X(a, CALLBACK, SINGULAR, STRING,   path,              6) \
X(a, STATIC,   SINGULAR, BOOL,     has_start_cmd_id,   7) \
X(a, STATIC,   SINGULAR, UINT32,   start_cmd_id,      8) \
X(a, STATIC,   SINGULAR, UENUM,    type,              9)
#define connect2_TransferInfoPayload_CALLBACK pb_default_field_callback
#define connect2_TransferInfoPayload_DEFAULT NULL

#define connect2_FinishedPayload_FIELDLIST(X, a) \

#define connect2_FinishedPayload_CALLBACK NULL
#define connect2_FinishedPayload_DEFAULT NULL

#define connect2_FailedPayload_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   reason,            1)
#define connect2_FailedPayload_CALLBACK pb_default_field_callback
#define connect2_FailedPayload_DEFAULT NULL

#define connect2_TransferStoppedPayload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     has_start_cmd_id,   1) \
X(a, STATIC,   SINGULAR, UINT32,   start_cmd_id,      2)
#define connect2_TransferStoppedPayload_CALLBACK NULL
#define connect2_TransferStoppedPayload_DEFAULT NULL

#define connect2_TransferAbortedPayload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     has_start_cmd_id,   1) \
X(a, STATIC,   SINGULAR, UINT32,   start_cmd_id,      2)
#define connect2_TransferAbortedPayload_CALLBACK NULL
#define connect2_TransferAbortedPayload_DEFAULT NULL

#define connect2_TransferFinishedPayload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     has_start_cmd_id,   1) \
X(a, STATIC,   SINGULAR, UINT32,   start_cmd_id,      2)
#define connect2_TransferFinishedPayload_CALLBACK NULL
#define connect2_TransferFinishedPayload_DEFAULT NULL

#define connect2_CancelableObject_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, BOOL,     canceled,          2)
#define connect2_CancelableObject_CALLBACK NULL
#define connect2_CancelableObject_DEFAULT NULL

#define connect2_CancelableChangedPayload_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  objects,           1)
#define connect2_CancelableChangedPayload_CALLBACK pb_default_field_callback
#define connect2_CancelableChangedPayload_DEFAULT NULL
#define connect2_CancelableChangedPayload_objects_MSGTYPE connect2_CancelableObject

#define connect2_StateChangedPayload_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     has_code,          1) \
X(a, CALLBACK, SINGULAR, STRING,   code,              2) \
X(a, STATIC,   SINGULAR, BOOL,     has_title,         3) \
X(a, CALLBACK, SINGULAR, STRING,   title,             4) \
X(a, STATIC,   SINGULAR, BOOL,     has_text,          5) \
X(a, CALLBACK, SINGULAR, STRING,   text,              6) \
X(a, CALLBACK, REPEATED, UENUM,    buttons,           7)
#define connect2_StateChangedPayload_CALLBACK pb_default_field_callback
#define connect2_StateChangedPayload_DEFAULT NULL

extern const pb_msgdesc_t connect2_EventEnvelope_msg;
extern const pb_msgdesc_t connect2_InfoPayload_msg;
extern const pb_msgdesc_t connect2_StorageInfo_msg;
extern const pb_msgdesc_t connect2_NetworkInfo_msg;
extern const pb_msgdesc_t connect2_ToolInfo_msg;
extern const pb_msgdesc_t connect2_EnclosureInfo_msg;
extern const pb_msgdesc_t connect2_MmuInfo_msg;
extern const pb_msgdesc_t connect2_AcceptedPayload_msg;
extern const pb_msgdesc_t connect2_RejectedPayload_msg;
extern const pb_msgdesc_t connect2_JobInfoPayload_msg;
extern const pb_msgdesc_t connect2_FileEntry_msg;
extern const pb_msgdesc_t connect2_FileInfoPayload_msg;
extern const pb_msgdesc_t connect2_FileChangedPayload_msg;
extern const pb_msgdesc_t connect2_TransferInfoPayload_msg;
extern const pb_msgdesc_t connect2_FinishedPayload_msg;
extern const pb_msgdesc_t connect2_FailedPayload_msg;
extern const pb_msgdesc_t connect2_TransferStoppedPayload_msg;
extern const pb_msgdesc_t connect2_TransferAbortedPayload_msg;
extern const pb_msgdesc_t connect2_TransferFinishedPayload_msg;
extern const pb_msgdesc_t connect2_CancelableObject_msg;
extern const pb_msgdesc_t connect2_CancelableChangedPayload_msg;
extern const pb_msgdesc_t connect2_StateChangedPayload_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define connect2_EventEnvelope_fields &connect2_EventEnvelope_msg
#define connect2_InfoPayload_fields &connect2_InfoPayload_msg
#define connect2_StorageInfo_fields &connect2_StorageInfo_msg
#define connect2_NetworkInfo_fields &connect2_NetworkInfo_msg
#define connect2_ToolInfo_fields &connect2_ToolInfo_msg
#define connect2_EnclosureInfo_fields &connect2_EnclosureInfo_msg
#define connect2_MmuInfo_fields &connect2_MmuInfo_msg
#define connect2_AcceptedPayload_fields &connect2_AcceptedPayload_msg
#define connect2_RejectedPayload_fields &connect2_RejectedPayload_msg
#define connect2_JobInfoPayload_fields &connect2_JobInfoPayload_msg
#define connect2_FileEntry_fields &connect2_FileEntry_msg
#define connect2_FileInfoPayload_fields &connect2_FileInfoPayload_msg
#define connect2_FileChangedPayload_fields &connect2_FileChangedPayload_msg
#define connect2_TransferInfoPayload_fields &connect2_TransferInfoPayload_msg
#define connect2_FinishedPayload_fields &connect2_FinishedPayload_msg
#define connect2_FailedPayload_fields &connect2_FailedPayload_msg
#define connect2_TransferStoppedPayload_fields &connect2_TransferStoppedPayload_msg
#define connect2_TransferAbortedPayload_fields &connect2_TransferAbortedPayload_msg
#define connect2_TransferFinishedPayload_fields &connect2_TransferFinishedPayload_msg
#define connect2_CancelableObject_fields &connect2_CancelableObject_msg
#define connect2_CancelableChangedPayload_fields &connect2_CancelableChangedPayload_msg
#define connect2_StateChangedPayload_fields &connect2_StateChangedPayload_msg

/* Maximum encoded size of messages (where known) */
/* connect2_EventEnvelope_size depends on runtime parameters */
/* connect2_InfoPayload_size depends on runtime parameters */
/* connect2_StorageInfo_size depends on runtime parameters */
/* connect2_NetworkInfo_size depends on runtime parameters */
/* connect2_ToolInfo_size depends on runtime parameters */
/* connect2_EnclosureInfo_size depends on runtime parameters */
/* connect2_MmuInfo_size depends on runtime parameters */
/* connect2_RejectedPayload_size depends on runtime parameters */
/* connect2_JobInfoPayload_size depends on runtime parameters */
/* connect2_FileEntry_size depends on runtime parameters */
/* connect2_FileInfoPayload_size depends on runtime parameters */
/* connect2_FileChangedPayload_size depends on runtime parameters */
/* connect2_TransferInfoPayload_size depends on runtime parameters */
/* connect2_FailedPayload_size depends on runtime parameters */
/* connect2_CancelableChangedPayload_size depends on runtime parameters */
/* connect2_StateChangedPayload_size depends on runtime parameters */
#define CONNECT2_EVENT_PB_H_MAX_SIZE             connect2_TransferStoppedPayload_size
#define connect2_AcceptedPayload_size            0
#define connect2_CancelableObject_size           8
#define connect2_FinishedPayload_size            0
#define connect2_TransferAbortedPayload_size     8
#define connect2_TransferFinishedPayload_size    8
#define connect2_TransferStoppedPayload_size     8

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
