/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "event.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(connect2_EventEnvelope, connect2_EventEnvelope, 2)


PB_BIND(connect2_InfoPayload, connect2_InfoPayload, 2)


PB_BIND(connect2_StorageInfo, connect2_StorageInfo, AUTO)


PB_BIND(connect2_NetworkInfo, connect2_NetworkInfo, AUTO)


PB_BIND(connect2_ToolInfo, connect2_ToolInfo, AUTO)


PB_BIND(connect2_EnclosureInfo, connect2_EnclosureInfo, AUTO)


PB_BIND(connect2_MmuInfo, connect2_MmuInfo, AUTO)


PB_BIND(connect2_AcceptedPayload, connect2_AcceptedPayload, AUTO)


PB_BIND(connect2_RejectedPayload, connect2_RejectedPayload, AUTO)


PB_BIND(connect2_JobInfoPayload, connect2_JobInfoPayload, AUTO)


PB_BIND(connect2_FileEntry, connect2_FileEntry, AUTO)


PB_BIND(connect2_FileInfoPayload, connect2_FileInfoPayload, AUTO)


PB_BIND(connect2_FileChangedPayload, connect2_FileChangedPayload, AUTO)


PB_BIND(connect2_TransferInfoPayload, connect2_TransferInfoPayload, AUTO)


PB_BIND(connect2_FinishedPayload, connect2_FinishedPayload, AUTO)


PB_BIND(connect2_FailedPayload, connect2_FailedPayload, AUTO)


PB_BIND(connect2_TransferStoppedPayload, connect2_TransferStoppedPayload, AUTO)


PB_BIND(connect2_TransferAbortedPayload, connect2_TransferAbortedPayload, AUTO)


PB_BIND(connect2_TransferFinishedPayload, connect2_TransferFinishedPayload, AUTO)


PB_BIND(connect2_CancelableObject, connect2_CancelableObject, AUTO)


PB_BIND(connect2_CancelableChangedPayload, connect2_CancelableChangedPayload, AUTO)


PB_BIND(connect2_StateChangedPayload, connect2_StateChangedPayload, AUTO)









