/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_CONNECT2_GCODE_PB_H_INCLUDED
#define PB_CONNECT2_GCODE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Raw G-code execution command sent from proxy/server to printer.

 MQTT topic:
   v1/devices/printers/<device_id>/gcode

 Legacy Connect WebSocket mapping:
 - force=false corresponds to frame type 'G'
 - force=true  corresponds to frame type 'F' */
typedef struct _connect2_GcodeCommandEnvelope {
    /* Legacy command id associated with the request. */
    uint32_t command_id;
    /* False = normal G-code execute ('G'), true = forced execute ('F'). */
    bool force;
    /* Raw G-code payload (single or multi-line text). */
    char gcode[2049];
} connect2_GcodeCommandEnvelope;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define connect2_GcodeCommandEnvelope_init_default {0, 0, ""}
#define connect2_GcodeCommandEnvelope_init_zero  {0, 0, ""}

/* Field tags (for use in manual encoding/decoding) */
#define connect2_GcodeCommandEnvelope_command_id_tag 1
#define connect2_GcodeCommandEnvelope_force_tag  2
#define connect2_GcodeCommandEnvelope_gcode_tag  3

/* Struct field encoding specification for nanopb */
#define connect2_GcodeCommandEnvelope_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   command_id,        1) \
X(a, STATIC,   SINGULAR, BOOL,     force,             2) \
X(a, STATIC,   SINGULAR, STRING,   gcode,             3)
#define connect2_GcodeCommandEnvelope_CALLBACK NULL
#define connect2_GcodeCommandEnvelope_DEFAULT NULL

extern const pb_msgdesc_t connect2_GcodeCommandEnvelope_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define connect2_GcodeCommandEnvelope_fields &connect2_GcodeCommandEnvelope_msg

/* Maximum encoded size of messages (where known) */
#define CONNECT2_GCODE_PB_H_MAX_SIZE             connect2_GcodeCommandEnvelope_size
#define connect2_GcodeCommandEnvelope_size       2059

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
