/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "gcode.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(connect2_GcodeCommandEnvelope, connect2_GcodeCommandEnvelope, 2)



