/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "info_event.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(InfoEvent, InfoEvent, 2)


PB_BIND(InfoData, InfoData, 2)


PB_BIND(Storage, Storage, AUTO)


PB_BIND(NetworkInfo, NetworkInfo, AUTO)


PB_BIND(Tool, Tool, AUTO)


PB_BIND(Enclosure, Enclosure, 2)


PB_BIND(Mmu, Mmu, AUTO)



