/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_INFO_EVENT_PB_H_INCLUDED
#define PB_INFO_EVENT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Storage {
    char mountpoint[17];
    char type[9];
    bool read_only;
    uint64_t free_space;
    bool is_sfn;
} Storage;

typedef struct _NetworkInfo {
    char lan_mac[19];
    char lan_ipv4[17];
    char wifi_ssid[33];
    char wifi_mac[19];
    char wifi_ipv4[17];
    char hostname[21];
} NetworkInfo;

typedef struct _Tool {
    uint32_t slot;
    float nozzle_diameter;
    bool high_flow;
    bool hardened;
    char material[9];
} Tool;

typedef struct _Enclosure {
    bool enabled;
    bool printing_filtration;
    bool post_print;
    uint32_t post_print_filtration_time;
    uint32_t filter_lifetime;
    pb_size_t filtration_filaments_count;
    char filtration_filaments[32][33];
} Enclosure;

typedef struct _Mmu {
    bool enabled;
    char version[17];
} Mmu;

typedef struct _InfoData {
    char firmware[65];
    char printer_type[17];
    char sn[33];
    bool appendix;
    char fingerprint[51];
    float nozzle_diameter;
    bool transfer_paused;
    char api_key[17];
    pb_size_t storages_count;
    Storage storages[1];
    bool has_network_info;
    NetworkInfo network_info;
    pb_size_t tools_count;
    Tool tools[5];
    bool has_enclosure;
    Enclosure enclosure;
    bool has_mmu;
    Mmu mmu;
    bool addon_power;
    uint32_t slots;
} InfoData;

typedef struct _InfoEvent {
    char event[17];
    char state[17];
    uint32_t dialog_id;
    bool has_data;
    InfoData data;
} InfoEvent;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define InfoEvent_init_default                   {"", "", 0, false, InfoData_init_default}
#define InfoData_init_default                    {"", "", "", 0, "", 0, 0, "", 0, {Storage_init_default}, false, NetworkInfo_init_default, 0, {Tool_init_default, Tool_init_default, Tool_init_default, Tool_init_default, Tool_init_default}, false, Enclosure_init_default, false, Mmu_init_default, 0, 0}
#define Storage_init_default                     {"", "", 0, 0, 0}
#define NetworkInfo_init_default                 {"", "", "", "", "", ""}
#define Tool_init_default                        {0, 0, 0, 0, ""}
#define Enclosure_init_default                   {0, 0, 0, 0, 0, 0, {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}}
#define Mmu_init_default                         {0, ""}
#define InfoEvent_init_zero                      {"", "", 0, false, InfoData_init_zero}
#define InfoData_init_zero                       {"", "", "", 0, "", 0, 0, "", 0, {Storage_init_zero}, false, NetworkInfo_init_zero, 0, {Tool_init_zero, Tool_init_zero, Tool_init_zero, Tool_init_zero, Tool_init_zero}, false, Enclosure_init_zero, false, Mmu_init_zero, 0, 0}
#define Storage_init_zero                        {"", "", 0, 0, 0}
#define NetworkInfo_init_zero                    {"", "", "", "", "", ""}
#define Tool_init_zero                           {0, 0, 0, 0, ""}
#define Enclosure_init_zero                      {0, 0, 0, 0, 0, 0, {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}}
#define Mmu_init_zero                            {0, ""}

/* Field tags (for use in manual encoding/decoding) */
#define Storage_mountpoint_tag                   1
#define Storage_type_tag                         2
#define Storage_read_only_tag                    3
#define Storage_free_space_tag                   4
#define Storage_is_sfn_tag                       5
#define NetworkInfo_lan_mac_tag                  1
#define NetworkInfo_lan_ipv4_tag                 2
#define NetworkInfo_wifi_ssid_tag                3
#define NetworkInfo_wifi_mac_tag                 4
#define NetworkInfo_wifi_ipv4_tag                5
#define NetworkInfo_hostname_tag                 6
#define Tool_slot_tag                            1
#define Tool_nozzle_diameter_tag                 2
#define Tool_high_flow_tag                       3
#define Tool_hardened_tag                        4
#define Tool_material_tag                        5
#define Enclosure_enabled_tag                    1
#define Enclosure_printing_filtration_tag        2
#define Enclosure_post_print_tag                 3
#define Enclosure_post_print_filtration_time_tag 4
#define Enclosure_filter_lifetime_tag            5
#define Enclosure_filtration_filaments_tag       6
#define Mmu_enabled_tag                          1
#define Mmu_version_tag                          2
#define InfoData_firmware_tag                    1
#define InfoData_printer_type_tag                2
#define InfoData_sn_tag                          3
#define InfoData_appendix_tag                    4
#define InfoData_fingerprint_tag                 5
#define InfoData_nozzle_diameter_tag             6
#define InfoData_transfer_paused_tag             7
#define InfoData_api_key_tag                     8
#define InfoData_storages_tag                    9
#define InfoData_network_info_tag                10
#define InfoData_tools_tag                       11
#define InfoData_enclosure_tag                   12
#define InfoData_mmu_tag                         13
#define InfoData_addon_power_tag                 14
#define InfoData_slots_tag                       15
#define InfoEvent_event_tag                      1
#define InfoEvent_state_tag                      2
#define InfoEvent_dialog_id_tag                  3
#define InfoEvent_data_tag                       4

/* Struct field encoding specification for nanopb */
#define InfoEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   event,             1) \
X(a, STATIC,   SINGULAR, STRING,   state,             2) \
X(a, STATIC,   SINGULAR, UINT32,   dialog_id,         3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  data,              4)
#define InfoEvent_CALLBACK NULL
#define InfoEvent_DEFAULT NULL
#define InfoEvent_data_MSGTYPE InfoData

#define InfoData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   firmware,          1) \
X(a, STATIC,   SINGULAR, STRING,   printer_type,      2) \
X(a, STATIC,   SINGULAR, STRING,   sn,                3) \
X(a, STATIC,   SINGULAR, BOOL,     appendix,          4) \
X(a, STATIC,   SINGULAR, STRING,   fingerprint,       5) \
X(a, STATIC,   SINGULAR, FLOAT,    nozzle_diameter,   6) \
X(a, STATIC,   SINGULAR, BOOL,     transfer_paused,   7) \
X(a, STATIC,   SINGULAR, STRING,   api_key,           8) \
X(a, STATIC,   REPEATED, MESSAGE,  storages,          9) \
X(a, STATIC,   OPTIONAL, MESSAGE,  network_info,     10) \
X(a, STATIC,   REPEATED, MESSAGE,  tools,            11) \
X(a, STATIC,   OPTIONAL, MESSAGE,  enclosure,        12) \
X(a, STATIC,   OPTIONAL, MESSAGE,  mmu,              13) \
X(a, STATIC,   SINGULAR, BOOL,     addon_power,      14) \
X(a, STATIC,   SINGULAR, UINT32,   slots,            15)
#define InfoData_CALLBACK NULL
#define InfoData_DEFAULT NULL
#define InfoData_storages_MSGTYPE Storage
#define InfoData_network_info_MSGTYPE NetworkInfo
#define InfoData_tools_MSGTYPE Tool
#define InfoData_enclosure_MSGTYPE Enclosure
#define InfoData_mmu_MSGTYPE Mmu

#define Storage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   mountpoint,        1) \
X(a, STATIC,   SINGULAR, STRING,   type,              2) \
X(a, STATIC,   SINGULAR, BOOL,     read_only,         3) \
X(a, STATIC,   SINGULAR, UINT64,   free_space,        4) \
X(a, STATIC,   SINGULAR, BOOL,     is_sfn,            5)
#define Storage_CALLBACK NULL
#define Storage_DEFAULT NULL

#define NetworkInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   lan_mac,           1) \
X(a, STATIC,   SINGULAR, STRING,   lan_ipv4,          2) \
X(a, STATIC,   SINGULAR, STRING,   wifi_ssid,         3) \
X(a, STATIC,   SINGULAR, STRING,   wifi_mac,          4) \
X(a, STATIC,   SINGULAR, STRING,   wifi_ipv4,         5) \
X(a, STATIC,   SINGULAR, STRING,   hostname,          6)
#define NetworkInfo_CALLBACK NULL
#define NetworkInfo_DEFAULT NULL

#define Tool_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   slot,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    nozzle_diameter,   2) \
X(a, STATIC,   SINGULAR, BOOL,     high_flow,         3) \
X(a, STATIC,   SINGULAR, BOOL,     hardened,          4) \
X(a, STATIC,   SINGULAR, STRING,   material,          5)
#define Tool_CALLBACK NULL
#define Tool_DEFAULT NULL

#define Enclosure_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           1) \
X(a, STATIC,   SINGULAR, BOOL,     printing_filtration,   2) \
X(a, STATIC,   SINGULAR, BOOL,     post_print,        3) \
X(a, STATIC,   SINGULAR, UINT32,   post_print_filtration_time,   4) \
X(a, STATIC,   SINGULAR, UINT32,   filter_lifetime,   5) \
X(a, STATIC,   REPEATED, STRING,   filtration_filaments,   6)
#define Enclosure_CALLBACK NULL
#define Enclosure_DEFAULT NULL

#define Mmu_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           1) \
X(a, STATIC,   SINGULAR, STRING,   version,           2)
#define Mmu_CALLBACK NULL
#define Mmu_DEFAULT NULL

extern const pb_msgdesc_t InfoEvent_msg;
extern const pb_msgdesc_t InfoData_msg;
extern const pb_msgdesc_t Storage_msg;
extern const pb_msgdesc_t NetworkInfo_msg;
extern const pb_msgdesc_t Tool_msg;
extern const pb_msgdesc_t Enclosure_msg;
extern const pb_msgdesc_t Mmu_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define InfoEvent_fields &InfoEvent_msg
#define InfoData_fields &InfoData_msg
#define Storage_fields &Storage_msg
#define NetworkInfo_fields &NetworkInfo_msg
#define Tool_fields &Tool_msg
#define Enclosure_fields &Enclosure_msg
#define Mmu_fields &Mmu_msg

/* Maximum encoded size of messages (where known) */
#define Enclosure_size                           1106
#define INFO_EVENT_PB_H_MAX_SIZE                 InfoEvent_size
#define InfoData_size                            1652
#define InfoEvent_size                           1697
#define Mmu_size                                 20
#define NetworkInfo_size                         132
#define Storage_size                             43
#define Tool_size                                25

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
