/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "info_event.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(InfoEvent, InfoEvent, 2)


PB_BIND(InfoData, InfoData, 2)


PB_BIND(Storage, Storage, AUTO)


PB_BIND(NetworkInfo, NetworkInfo, AUTO)


PB_BIND(Tool, Tool, AUTO)


PB_BIND(Enclosure, Enclosure, 2)


PB_BIND(Mmu, Mmu, AUTO)


PB_BIND(FileEntry, FileEntry, AUTO)


PB_BIND(FileInfo, FileInfo, 2)


PB_BIND(FileChanged, FileChanged, 2)


PB_BIND(Rejected, Rejected, AUTO)


PB_BIND(JobInfo, JobInfo, AUTO)


PB_BIND(JobInfoEvent, JobInfoEvent, 2)


PB_BIND(FinishedEvent, FinishedEvent, AUTO)


PB_BIND(FailedEvent, FailedEvent, AUTO)


PB_BIND(StateChangedEvent, StateChangedEvent, AUTO)


PB_BIND(FileInfoEvent, FileInfoEvent, 2)


PB_BIND(FileChangedEvent, FileChangedEvent, 2)


PB_BIND(RejectedEvent, RejectedEvent, AUTO)



