/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_CONNECT2_TELEMETRY_PB_H_INCLUDED
#define PB_CONNECT2_TELEMETRY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _connect2_TelemetryEnvelope {
    /* Legacy JSON top-level key: state */
    char state[17];
    bool has_job_id;
    uint32_t job_id;
    bool has_time_printing;
    uint32_t time_printing;
    bool has_time_remaining;
    uint32_t time_remaining;
    bool has_filament_change_in;
    uint32_t filament_change_in;
    bool has_progress;
    uint32_t progress;
    bool has_temp_nozzle;
    float temp_nozzle;
    bool has_temp_bed;
    float temp_bed;
    bool has_target_nozzle;
    float target_nozzle;
    bool has_target_bed;
    float target_bed;
    bool has_speed;
    uint32_t speed;
    bool has_flow;
    uint32_t flow;
    bool has_material;
    char material[33];
    bool has_axis_x;
    float axis_x;
    bool has_axis_y;
    float axis_y;
    bool has_axis_z;
    float axis_z;
    bool has_fan_extruder;
    uint32_t fan_extruder;
    bool has_fan_print;
    uint32_t fan_print;
    bool has_filament;
    float filament;
    bool has_command_id;
    uint32_t command_id;
    bool has_dialog_id;
    uint32_t dialog_id;
    bool has_transfer_id;
    uint32_t transfer_id;
    bool has_transfer_transferred;
    uint64_t transfer_transferred;
    bool has_transfer_time_remaining;
    uint32_t transfer_time_remaining;
    bool has_transfer_progress;
    float transfer_progress;
} connect2_TelemetryEnvelope;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define connect2_TelemetryEnvelope_init_default  {"", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define connect2_TelemetryEnvelope_init_zero     {"", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define connect2_TelemetryEnvelope_state_tag     1
#define connect2_TelemetryEnvelope_has_job_id_tag 2
#define connect2_TelemetryEnvelope_job_id_tag    3
#define connect2_TelemetryEnvelope_has_time_printing_tag 4
#define connect2_TelemetryEnvelope_time_printing_tag 5
#define connect2_TelemetryEnvelope_has_time_remaining_tag 6
#define connect2_TelemetryEnvelope_time_remaining_tag 7
#define connect2_TelemetryEnvelope_has_filament_change_in_tag 8
#define connect2_TelemetryEnvelope_filament_change_in_tag 9
#define connect2_TelemetryEnvelope_has_progress_tag 10
#define connect2_TelemetryEnvelope_progress_tag  11
#define connect2_TelemetryEnvelope_has_temp_nozzle_tag 12
#define connect2_TelemetryEnvelope_temp_nozzle_tag 13
#define connect2_TelemetryEnvelope_has_temp_bed_tag 14
#define connect2_TelemetryEnvelope_temp_bed_tag  15
#define connect2_TelemetryEnvelope_has_target_nozzle_tag 16
#define connect2_TelemetryEnvelope_target_nozzle_tag 17
#define connect2_TelemetryEnvelope_has_target_bed_tag 18
#define connect2_TelemetryEnvelope_target_bed_tag 19
#define connect2_TelemetryEnvelope_has_speed_tag 20
#define connect2_TelemetryEnvelope_speed_tag     21
#define connect2_TelemetryEnvelope_has_flow_tag  22
#define connect2_TelemetryEnvelope_flow_tag      23
#define connect2_TelemetryEnvelope_has_material_tag 24
#define connect2_TelemetryEnvelope_material_tag  25
#define connect2_TelemetryEnvelope_has_axis_x_tag 26
#define connect2_TelemetryEnvelope_axis_x_tag    27
#define connect2_TelemetryEnvelope_has_axis_y_tag 28
#define connect2_TelemetryEnvelope_axis_y_tag    29
#define connect2_TelemetryEnvelope_has_axis_z_tag 30
#define connect2_TelemetryEnvelope_axis_z_tag    31
#define connect2_TelemetryEnvelope_has_fan_extruder_tag 32
#define connect2_TelemetryEnvelope_fan_extruder_tag 33
#define connect2_TelemetryEnvelope_has_fan_print_tag 34
#define connect2_TelemetryEnvelope_fan_print_tag 35
#define connect2_TelemetryEnvelope_has_filament_tag 36
#define connect2_TelemetryEnvelope_filament_tag  37
#define connect2_TelemetryEnvelope_has_command_id_tag 38
#define connect2_TelemetryEnvelope_command_id_tag 39
#define connect2_TelemetryEnvelope_has_dialog_id_tag 40
#define connect2_TelemetryEnvelope_dialog_id_tag 41
#define connect2_TelemetryEnvelope_has_transfer_id_tag 42
#define connect2_TelemetryEnvelope_transfer_id_tag 43
#define connect2_TelemetryEnvelope_has_transfer_transferred_tag 44
#define connect2_TelemetryEnvelope_transfer_transferred_tag 45
#define connect2_TelemetryEnvelope_has_transfer_time_remaining_tag 46
#define connect2_TelemetryEnvelope_transfer_time_remaining_tag 47
#define connect2_TelemetryEnvelope_has_transfer_progress_tag 48
#define connect2_TelemetryEnvelope_transfer_progress_tag 49

/* Struct field encoding specification for nanopb */
#define connect2_TelemetryEnvelope_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   state,             1) \
X(a, STATIC,   SINGULAR, BOOL,     has_job_id,        2) \
X(a, STATIC,   SINGULAR, UINT32,   job_id,            3) \
X(a, STATIC,   SINGULAR, BOOL,     has_time_printing,   4) \
X(a, STATIC,   SINGULAR, UINT32,   time_printing,     5) \
X(a, STATIC,   SINGULAR, BOOL,     has_time_remaining,   6) \
X(a, STATIC,   SINGULAR, UINT32,   time_remaining,    7) \
X(a, STATIC,   SINGULAR, BOOL,     has_filament_change_in,   8) \
X(a, STATIC,   SINGULAR, UINT32,   filament_change_in,   9) \
X(a, STATIC,   SINGULAR, BOOL,     has_progress,     10) \
X(a, STATIC,   SINGULAR, UINT32,   progress,         11) \
X(a, STATIC,   SINGULAR, BOOL,     has_temp_nozzle,  12) \
X(a, STATIC,   SINGULAR, FLOAT,    temp_nozzle,      13) \
X(a, STATIC,   SINGULAR, BOOL,     has_temp_bed,     14) \
X(a, STATIC,   SINGULAR, FLOAT,    temp_bed,         15) \
X(a, STATIC,   SINGULAR, BOOL,     has_target_nozzle,  16) \
X(a, STATIC,   SINGULAR, FLOAT,    target_nozzle,    17) \
X(a, STATIC,   SINGULAR, BOOL,     has_target_bed,   18) \
X(a, STATIC,   SINGULAR, FLOAT,    target_bed,       19) \
X(a, STATIC,   SINGULAR, BOOL,     has_speed,        20) \
X(a, STATIC,   SINGULAR, UINT32,   speed,            21) \
X(a, STATIC,   SINGULAR, BOOL,     has_flow,         22) \
X(a, STATIC,   SINGULAR, UINT32,   flow,             23) \
X(a, STATIC,   SINGULAR, BOOL,     has_material,     24) \
X(a, STATIC,   SINGULAR, STRING,   material,         25) \
X(a, STATIC,   SINGULAR, BOOL,     has_axis_x,       26) \
X(a, STATIC,   SINGULAR, FLOAT,    axis_x,           27) \
X(a, STATIC,   SINGULAR, BOOL,     has_axis_y,       28) \
X(a, STATIC,   SINGULAR, FLOAT,    axis_y,           29) \
X(a, STATIC,   SINGULAR, BOOL,     has_axis_z,       30) \
X(a, STATIC,   SINGULAR, FLOAT,    axis_z,           31) \
X(a, STATIC,   SINGULAR, BOOL,     has_fan_extruder,  32) \
X(a, STATIC,   SINGULAR, UINT32,   fan_extruder,     33) \
X(a, STATIC,   SINGULAR, BOOL,     has_fan_print,    34) \
X(a, STATIC,   SINGULAR, UINT32,   fan_print,        35) \
X(a, STATIC,   SINGULAR, BOOL,     has_filament,     36) \
X(a, STATIC,   SINGULAR, FLOAT,    filament,         37) \
X(a, STATIC,   SINGULAR, BOOL,     has_command_id,   38) \
X(a, STATIC,   SINGULAR, UINT32,   command_id,       39) \
X(a, STATIC,   SINGULAR, BOOL,     has_dialog_id,    40) \
X(a, STATIC,   SINGULAR, UINT32,   dialog_id,        41) \
X(a, STATIC,   SINGULAR, BOOL,     has_transfer_id,  42) \
X(a, STATIC,   SINGULAR, UINT32,   transfer_id,      43) \
X(a, STATIC,   SINGULAR, BOOL,     has_transfer_transferred,  44) \
X(a, STATIC,   SINGULAR, UINT64,   transfer_transferred,  45) \
X(a, STATIC,   SINGULAR, BOOL,     has_transfer_time_remaining,  46) \
X(a, STATIC,   SINGULAR, UINT32,   transfer_time_remaining,  47) \
X(a, STATIC,   SINGULAR, BOOL,     has_transfer_progress,  48) \
X(a, STATIC,   SINGULAR, FLOAT,    transfer_progress,  49)
#define connect2_TelemetryEnvelope_CALLBACK NULL
#define connect2_TelemetryEnvelope_DEFAULT NULL

extern const pb_msgdesc_t connect2_TelemetryEnvelope_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define connect2_TelemetryEnvelope_fields &connect2_TelemetryEnvelope_msg

/* Maximum encoded size of messages (where known) */
#define CONNECT2_TELEMETRY_PB_H_MAX_SIZE         connect2_TelemetryEnvelope_size
#define connect2_TelemetryEnvelope_size          268

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
