# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcommand.proto\"\x86\x02\n\x07\x43ommand\x12\x1b\n\x04type\x18\x01 \x01(\x0e\x32\r.Command.Type\x12\x12\n\ncommand_id\x18\x02 \x01(\r\x12\x0c\n\x04path\x18\x03 \x01(\t\x12\x0e\n\x06job_id\x18\x04 \x01(\r\"\xab\x01\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\r\n\tSEND_INFO\x10\x01\x12\x12\n\x0eSEND_FILE_INFO\x10\x02\x12\x11\n\rSEND_JOB_INFO\x10\x07\x12\x0f\n\x0bSTART_PRINT\x10\x03\x12\x0e\n\nSTOP_PRINT\x10\x04\x12\x0f\n\x0bPAUSE_PRINT\x10\x05\x12\x10\n\x0cRESUME_PRINT\x10\x06\x12\x11\n\rRESET_PRINTER\x10\x08\x12\t\n\x05RESET\x10\tb\x06proto3')



_COMMAND = DESCRIPTOR.message_types_by_name['Command']
_COMMAND_TYPE = _COMMAND.enum_types_by_name['Type']
Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND,
  '__module__' : 'command_pb2'
  # @@protoc_insertion_point(class_scope:Command)
  })
_sym_db.RegisterMessage(Command)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMAND._serialized_start=18
  _COMMAND._serialized_end=280
  _COMMAND_TYPE._serialized_start=109
  _COMMAND_TYPE._serialized_end=280
# @@protoc_insertion_point(module_scope)
