persistence false

log_dest stdout
log_type error
log_type warning
log_type notice
log_type information

per_listener_settings false
allow_anonymous false

listener 8883
protocol mqtt
cafile /certs/ca.crt
certfile /certs/server.crt
keyfile /certs/server.key
require_certificate false
tls_version tlsv1.2
ciphers ECDHE-ECDSA-AES128-GCM-SHA256

plugin /usr/lib/x86_64-linux-gnu/mosquitto_dynamic_security.so
plugin_opt_config_file /mosquitto/data/dynamic-security.json
plugin_opt_verbose true
